/**
 * ICS (iCalendar) Export — counselor downloads a .ics of her schedule and
 * imports / subscribes to it from Google Calendar / Apple Calendar / Outlook.
 *
 * FERPA posture: by default, student names are scrubbed from event titles.
 * Counselor opts in to include names ("show student names in calendar feed")
 * via Settings — Beacon shows a one-line "may sit in your personal calendar
 * vendor's cloud" warning before flipping that on.
 *
 * Local mode: file download (works fully offline). Subscription URL would
 * require a server endpoint — out of scope for v1.
 */

import { db } from './db';
import { format, addWeeks, parseISO } from 'date-fns';

const PRODID = '-//Clear Path Education Group//Beacon Counselor//EN';

/** Format a Date as ICS local-time (no Z suffix; user's calendar handles tz). */
function icsLocal(date) {
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  const hh = String(date.getHours()).padStart(2, '0');
  const mi = String(date.getMinutes()).padStart(2, '0');
  const ss = String(date.getSeconds()).padStart(2, '0');
  return `${yyyy}${mm}${dd}T${hh}${mi}${ss}`;
}

/** Escape ICS field value: \\n, escape commas / semicolons / backslashes. */
function escapeIcs(s) {
  return String(s || '')
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/** Combine YYYY-MM-DD + HH:MM[:SS] into a Date object (local time). */
function combineDateTime(dateStr, timeStr) {
  if (!dateStr || !timeStr) return null;
  const parts = timeStr.split(':');
  const d = parseISO(dateStr);
  d.setHours(parseInt(parts[0] || 0, 10), parseInt(parts[1] || 0, 10), parseInt(parts[2] || 0, 10), 0);
  return d;
}

/** Build a single VEVENT block from a counseling session. */
function sessionToVEvent(session, group, includeNames, group_member_names) {
  const start = combineDateTime(session.session_date, session.start_time);
  const end = combineDateTime(session.session_date, session.end_time);
  if (!start || !end) return null;
  const groupLabel = group?.name || 'Counseling Session';
  let title;
  if (includeNames && group_member_names && group_member_names.length > 0) {
    title = `${groupLabel}: ${group_member_names.join(', ')}`;
  } else if (group?.name) {
    title = `${groupLabel}`;
  } else {
    title = 'Counseling Session';
  }
  const desc = [
    `Status: ${session.status || 'Scheduled'}`,
    session.notes ? `Notes: ${session.notes}` : null,
    'Generated by Beacon (no student data left your device)',
  ].filter(Boolean).join('\\n');
  return [
    'BEGIN:VEVENT',
    `UID:beacon-session-${session.id}@beacon.clearpathedgroup.com`,
    `DTSTAMP:${icsLocal(new Date())}`,
    `DTSTART:${icsLocal(start)}`,
    `DTEND:${icsLocal(end)}`,
    `SUMMARY:${escapeIcs(title)}`,
    `DESCRIPTION:${escapeIcs(desc)}`,
    'END:VEVENT',
  ].join('\r\n');
}

/** Schedule blocks repeat weekly across the school year — emit recurring events. */
function blockToVEvent(block, scheduleStart, scheduleEnd) {
  // day_of_week: 0=Sun ... 6=Sat
  const dow = block.day_of_week;
  if (dow == null) return null;

  // Find the first occurrence on or after scheduleStart
  const first = new Date(scheduleStart);
  while (first.getDay() !== dow) {
    first.setDate(first.getDate() + 1);
  }
  const [sH, sM] = (block.start_time || '08:00').split(':').map(Number);
  const [eH, eM] = (block.end_time || '09:00').split(':').map(Number);
  first.setHours(sH, sM, 0, 0);
  const end = new Date(first);
  end.setHours(eH, eM, 0, 0);

  // Final repetition date in YYYYMMDDT235959 form for UNTIL
  const until = new Date(scheduleEnd);
  until.setHours(23, 59, 59, 0);

  return [
    'BEGIN:VEVENT',
    `UID:beacon-block-${block.id}@beacon.clearpathedgroup.com`,
    `DTSTAMP:${icsLocal(new Date())}`,
    `DTSTART:${icsLocal(first)}`,
    `DTEND:${icsLocal(end)}`,
    `RRULE:FREQ=WEEKLY;UNTIL=${icsLocal(until)}`,
    `SUMMARY:${escapeIcs(block.label || 'Counseling Block')}`,
    `DESCRIPTION:${escapeIcs(`Recurring counseling block. Generated by Beacon.`)}`,
    'END:VEVENT',
  ].join('\r\n');
}

/** Follow-ups → all-day reminder events on the due date. */
function followUpToVEvent(fu) {
  if (!fu.due_at) return null;
  const dueDate = new Date(fu.due_at);
  if (isNaN(dueDate.getTime())) return null;
  return [
    'BEGIN:VEVENT',
    `UID:beacon-followup-${fu.id}@beacon.clearpathedgroup.com`,
    `DTSTAMP:${icsLocal(new Date())}`,
    `DTSTART:${icsLocal(dueDate)}`,
    `DTEND:${icsLocal(new Date(dueDate.getTime() + 30 * 60_000))}`,
    `SUMMARY:${escapeIcs(`[Beacon] ${fu.title || 'Follow-up'}`)}`,
    `DESCRIPTION:${escapeIcs(fu.body || '')}`,
    'END:VEVENT',
  ].join('\r\n');
}

/**
 * Build the full ICS document for a counselor.
 * Includes: scheduled sessions in [start, end], recurring schedule blocks,
 * pending follow-ups.
 */
export async function buildCalendarIcs(counselorId, { includeNames = false, weeksAhead = 12 } = {}) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const start = today;
  const end = addWeeks(today, weeksAhead);

  const [{ data: sessions }, { data: blocks }, { data: followUps }, { data: groups }, { data: members }] = await Promise.all([
    db.select('sessions', {
      eq: { counselor_id: counselorId },
      gte: { session_date: format(start, 'yyyy-MM-dd') },
      lte: { session_date: format(end, 'yyyy-MM-dd') },
    }),
    db.select('campus_schedule_blocks', { eq: { counselor_id: counselorId } }),
    db.select('follow_ups', { eq: { counselor_id: counselorId, status: 'pending' } }),
    db.select('groups', { eq: { counselor_id: counselorId } }),
    db.select('group_members'),
  ]);

  const groupById = Object.fromEntries((groups || []).map((g) => [g.id, g]));
  const studentsById = {};
  if (includeNames) {
    const { data: students } = await db.select('students', { eq: { counselor_id: counselorId } });
    for (const s of students || []) studentsById[s.id] = s.name || s.preferred_name || '';
  }
  const membersByGroup = {};
  for (const m of members || []) {
    if (!membersByGroup[m.group_id]) membersByGroup[m.group_id] = [];
    membersByGroup[m.group_id].push(m.student_id);
  }

  const events = [];
  for (const s of sessions || []) {
    if (s.status === 'Cancelled') continue;
    const group = groupById[s.group_id];
    const memberIds = group ? membersByGroup[group.id] || [] : [];
    const memberNames = memberIds.map((id) => studentsById[id]).filter(Boolean);
    const ev = sessionToVEvent(s, group, includeNames, memberNames);
    if (ev) events.push(ev);
  }
  for (const b of blocks || []) {
    const ev = blockToVEvent(b, start, end);
    if (ev) events.push(ev);
  }
  for (const fu of followUps || []) {
    const ev = followUpToVEvent(fu);
    if (ev) events.push(ev);
  }

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:${PRODID}`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:Beacon Counselor Schedule`,
    `X-WR-CALDESC:Generated by Beacon. ${includeNames ? 'Includes student names — keep this file private.' : 'Student names anonymized.'}`,
    ...events,
    'END:VCALENDAR',
  ].join('\r\n');

  return lines;
}

export async function downloadCalendarIcs(counselorId, opts = {}) {
  const ics = await buildCalendarIcs(counselorId, opts);
  const blob = new Blob([ics], { type: 'text/calendar' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const dateLabel = format(new Date(), 'yyyy-MM-dd');
  a.download = `beacon-calendar-${dateLabel}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
