/**
 * Small group starter kits for elementary school counselors (K-5).
 * 6 complete session-by-session programs with real, usable content.
 */

export const GROUP_STARTER_KITS = [
  // ── Kit 1: Anger Management (8 sessions, grades 2-5) ──
  {
    id: 'kit-anger',
    title: 'Anger Management',
    description: 'An 8-session group helping students understand anger, identify triggers, and build a personal toolkit of calm-down strategies. Students learn that anger is a normal emotion but that they can choose how to express it.',
    grade_range: '2-5',
    session_count: 8,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'What Is Anger?',
        objective: 'Students will define anger, normalize it as a feeling everyone has, and identify what anger looks and feels like in their body.',
        opening_activity: 'Feelings check-in: each student picks a color from a pile of construction paper that matches their mood today and shares one word about why they chose it.',
        main_activity: 'Introduce the "Anger Iceberg" concept with a large poster. The tip above water is anger, and underneath are deeper feelings like embarrassment, hurt, fear, frustration, or loneliness. Students draw their own iceberg and write or draw the feelings they think hide underneath their anger. Share in pairs.',
        closing_checkout: 'Each student names one place in their body where they feel anger (tight fists, hot face, fast heartbeat). Counselor writes these on an anchor chart titled "My Body\'s Anger Signals."',
        take_home_challenge: 'This week, when you feel angry, pause and notice where you feel it in your body. Tell a trusted adult what you noticed.',
      },
      {
        session_number: 2,
        title: 'My Anger Triggers',
        objective: 'Students will identify personal anger triggers and understand that different people have different triggers.',
        opening_activity: 'Quick review of the anger iceberg. Ask: "Did anyone notice their body signals this week?" Share out.',
        main_activity: 'Give each student a paper volcano. On the outside, they write or draw situations that "set off" their volcano (being teased, losing a game, someone being unfair, getting blamed for something). Inside the volcano, they write how big their eruption usually is (1 = small rumble, 5 = full explosion). Discuss as a group: are everyone\'s triggers the same? Why do different things bother different people?',
        closing_checkout: 'Each student shares their number-one trigger and one thing they learned about someone else\'s trigger. "I didn\'t know that bothered you too!"',
        take_home_challenge: 'Keep a "Trigger Tracker" this week — write down one time you felt angry and what triggered it.',
      },
      {
        session_number: 3,
        title: 'The Anger Thermometer',
        objective: 'Students will rate anger intensity on a scale of 1-5 and recognize that different levels need different strategies.',
        opening_activity: 'Review trigger trackers from the week. Volunteers share what they noticed.',
        main_activity: 'Introduce the Anger Thermometer: 1 = annoyed (eye roll), 2 = frustrated (huffing), 3 = angry (raised voice), 4 = furious (wanting to hit/throw), 5 = out of control (meltdown). For each level, discuss what it looks like and sounds like. Then read 6 scenarios aloud — students hold up fingers to rate the anger level. Key insight: if you can catch yourself at a 1 or 2, it\'s much easier to calm down than at a 4 or 5.',
        closing_checkout: 'Students color their own thermometer and mark where they usually are when they "lose it." Goal: start using strategies earlier on the thermometer.',
        take_home_challenge: 'When you feel angry this week, try to name your number on the thermometer before you react.',
      },
      {
        session_number: 4,
        title: 'Calm-Down Strategies: Breathing and Movement',
        objective: 'Students will practice three physical calm-down strategies and identify which works best for their body.',
        opening_activity: 'Thermometer check-in: "What number are you right now? What number were you at your angriest moment this week?"',
        main_activity: 'Rotate through three stations (4 minutes each): Station 1 — Balloon Breathing: breathe in through the nose for 4 counts, out through the mouth for 6 counts, hands on belly to feel it expand. Station 2 — Wall Push-Ups: push hard against the wall 10 times to release physical tension, then shake out hands. Station 3 — Squeeze and Release: make tight fists for 5 seconds, then release; tense shoulders up to ears, then drop. Repeat 3 times. After all stations, discuss: which one helped YOUR body the most? Write it on an index card.',
        closing_checkout: 'Each student holds up their strategy card and says, "When I\'m angry, I\'m going to try ___."',
        take_home_challenge: 'Use your chosen strategy at least once this week when you feel your thermometer rising. Tell us how it went next time.',
      },
      {
        session_number: 5,
        title: 'Calm-Down Strategies: Thinking Tools',
        objective: 'Students will learn cognitive strategies for managing anger, including self-talk and perspective-taking.',
        opening_activity: 'Strategy report: who tried their breathing or movement strategy this week? What happened?',
        main_activity: 'Introduce "thinking tools" — strategies that happen in your mind. Tool 1: Positive Self-Talk. Replace "This is so unfair! I hate them!" with "I\'m upset right now, but I can handle this." Practice rewriting 4 angry thoughts into calmer ones. Tool 2: Counting Down. Count backwards from 10 before reacting — silently or aloud. Practice together. Tool 3: Perspective-Taking. "Is there another way to see this? Maybe they didn\'t mean it that way." Read two scenarios and practice seeing both sides. Students add their favorite thinking tool to their strategy card from last week.',
        closing_checkout: 'Round-robin: "My best body strategy is ___ and my best thinking strategy is ___."',
        take_home_challenge: 'Try combining a body strategy and a thinking strategy when you get angry this week. Notice if using both works better than one.',
      },
      {
        session_number: 6,
        title: 'Expressing Anger Respectfully',
        objective: 'Students will practice using I-Messages and assertive communication instead of aggressive or passive responses.',
        opening_activity: 'Act out a "wrong way" to express anger (yelling, name-calling, slamming things). Ask: "Did that solve the problem?" Then discuss what usually happens next (more trouble).',
        main_activity: 'Teach the I-Message formula: "I feel ___ when ___ because ___. I need ___." Model with a common scenario: "I feel frustrated when you take my pencil without asking because I need it for my work. I need you to ask first." Students pair up and practice with 4 scenario cards. After each practice, partners give feedback: "That sounded calm and clear" or "Try softening your voice a little." Counselor circulates and coaches.',
        closing_checkout: 'Each pair performs their best I-Message for the group. Group gives a thumbs-up if it sounds respectful.',
        take_home_challenge: 'Use an I-Message at home or at school when something bothers you. Write it down and bring it to our next session.',
      },
      {
        session_number: 7,
        title: 'Making a Plan: My Anger Action Steps',
        objective: 'Students will create a personalized anger management plan combining body strategies, thinking tools, and communication skills.',
        opening_activity: 'I-Message share: who used one this week? How did the other person respond?',
        main_activity: 'Each student creates their personal "Anger Action Plan" on a folded card. Page 1: My top 3 triggers (from Session 2). Page 2: My body\'s warning signals (from Session 1). Page 3: My calm-down strategies — one body tool, one thinking tool (from Sessions 4-5). Page 4: My I-Message template and one trusted adult I can talk to. Students decorate their cards. Counselor hole-punches and provides a key ring so students can flip through steps in order when angry.',
        closing_checkout: 'Students walk through their plan out loud with a partner: "First I notice ___, then I try ___, then I say ___."',
        take_home_challenge: 'Keep your Anger Action Plan in your desk or backpack. Use it at least once before our final session.',
      },
      {
        session_number: 8,
        title: 'Celebration and Practice',
        objective: 'Students will demonstrate anger management skills, celebrate growth, and commit to continuing their strategies.',
        opening_activity: 'Each student shares one success story from the past 7 weeks — a time they managed anger better than they would have before this group.',
        main_activity: 'Scenario relay: counselor reads 6 challenging anger scenarios. Students work in pairs to walk through their full Anger Action Plan for each one (notice the trigger, name the body signal, use a calm-down strategy, express feelings with an I-Message). After each scenario, the group votes on the most effective response. Then each student writes a letter to their "future angry self" with advice and encouragement.',
        closing_checkout: 'Certificate ceremony: each student receives a completion certificate. Group members share one positive thing they noticed about each other during the 8 weeks. Final thermometer check — where are you now?',
        take_home_challenge: 'Keep your Anger Action Plan and your letter to yourself. Read the letter next time you feel your thermometer rising above a 3.',
      },
    ],
  },

  // ── Kit 2: Friendship Skills (6 sessions, grades K-2) ──
  {
    id: 'kit-friendship',
    title: 'Friendship Skills',
    description: 'A 6-session group teaching young students the basics of making and keeping friends. Students practice sharing, taking turns, handling disagreements, and being a kind friend through games, role-play, and art.',
    grade_range: 'K-2',
    session_count: 6,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'What Makes a Good Friend?',
        objective: 'Students will identify qualities of a good friend and set group expectations.',
        opening_activity: 'Name game: each student says their name and one thing they like to do at recess. Counselor connects shared interests: "You both like tag — you could play together!"',
        main_activity: 'Read "Enemy Pie" by Derek Munson (or summarize the story). Discuss: what made the boys become friends? What do good friends do? Students brainstorm a list together (shares, listens, takes turns, is kind, includes others, says sorry). Each student traces their hand on paper and writes one friendship quality on each finger. Display hands on the wall as the group\'s "Friendship Pledge."',
        closing_checkout: 'Students put their hands in the center of the circle and say together: "We are going to be great friends!" Each student names one quality they want to work on.',
        take_home_challenge: 'Do one kind thing for someone at recess tomorrow. Come back ready to tell us about it.',
      },
      {
        session_number: 2,
        title: 'Sharing and Taking Turns',
        objective: 'Students will practice sharing materials and taking turns during a cooperative activity.',
        opening_activity: 'Kindness report: who did their kind thing at recess? What happened?',
        main_activity: 'Give each pair of students one set of crayons and one large piece of paper. They must draw a picture together but can only use ONE crayon at a time between them — they have to share and take turns. After 8 minutes, discuss: Was it hard to share? What helped? What made it frustrating? Then introduce two phrases: "Can I have a turn when you\'re done?" and "Sure, you can use it next." Practice saying both with a friendly voice. Role-play 3 sharing scenarios with puppets or stuffed animals.',
        closing_checkout: 'Each student shares their collaborative drawing and tells the group one thing their partner did that was a good friend move.',
        take_home_challenge: 'Practice saying "Can I have a turn when you\'re done?" this week instead of grabbing.',
      },
      {
        session_number: 3,
        title: 'Listening with Your Whole Body',
        objective: 'Students will demonstrate whole-body listening: eyes looking, ears listening, mouth quiet, hands still, body calm.',
        opening_activity: 'Counselor tells a very short story (30 seconds) while doing everything wrong — looking away, fidgeting, interrupting. Ask: "Was I being a good listener? What did I do wrong?"',
        main_activity: 'Teach "Whole Body Listening" with a body poster: eyes are looking at the speaker, ears are listening, mouth is quiet (waiting for your turn), hands are still (not poking or playing), body is calm (facing the speaker, feet on the floor). Practice in pairs: one student tells about their favorite animal for 30 seconds while the other demonstrates whole-body listening. Switch. Then play "Telephone" — whisper a sentence around the circle. Did it make it all the way? Good listening helps!',
        closing_checkout: 'Counselor gives each student a specific compliment about their listening: "I noticed you kept your eyes on your partner the whole time."',
        take_home_challenge: 'Practice whole-body listening when a teacher or parent is talking. See if they notice!',
      },
      {
        session_number: 4,
        title: 'Handling Disagreements',
        objective: 'Students will use a simple 3-step process to solve friendship problems: Stop, Talk, Solve.',
        opening_activity: 'Ask: "Has anyone ever had a disagreement with a friend?" (Hands will shoot up!) "Disagreements are normal — they don\'t mean the friendship is over. Today we learn how to fix them."',
        main_activity: 'Teach the 3-step process using a traffic light visual. RED = STOP: Take a breath. Don\'t yell or hit. YELLOW = TALK: Each person takes a turn saying what happened and how they feel. Use the sentence "I felt ___ when ___." GREEN = SOLVE: Think of a solution together. Can you take turns? Compromise? Say sorry? Practice with three puppet scenarios: (1) two students want the same swing, (2) a friend calls you a name, (3) someone won\'t let you play. Students suggest solutions for each.',
        closing_checkout: 'Each student says, "Next time I have a problem with a friend, the first thing I will do is ___" (answer should be STOP).',
        take_home_challenge: 'If you have a disagreement this week, try Stop-Talk-Solve before asking an adult. Tell us what happened next time.',
      },
      {
        session_number: 5,
        title: 'Including Others',
        objective: 'Students will practice inviting others to join activities and understand how exclusion feels.',
        opening_activity: 'Play a quick game but "forget" to invite one student (pre-arranged volunteer). After 30 seconds, stop. Ask the excluded student: "How did that feel?" Ask the group: "Did you notice? What could you have done?"',
        main_activity: 'Discuss why kids get left out (new, different, shy, someone is being mean) and why it hurts. Teach the "Invitation Sentence": "Do you want to play with us?" or "Come sit with me!" Students practice by role-playing 4 inclusion scenarios: a new student at lunch, a kid alone at recess, someone whose friend is absent, a student who is shy. After each scenario, the "included" student shares how it felt to be invited.',
        closing_checkout: 'Group makes an "Includer Pledge" poster. Each student signs it: "I promise to look for someone who needs a friend and invite them to join me."',
        take_home_challenge: 'Find one person at school who looks like they need a friend. Use your invitation sentence. Report back next session.',
      },
      {
        session_number: 6,
        title: 'Friendship Celebration',
        objective: 'Students will demonstrate friendship skills learned throughout the group and celebrate their growth.',
        opening_activity: 'Inclusion reports: who invited someone to play? What happened? How did it feel?',
        main_activity: 'Friendship Skills Relay: set up 4 stations that review all the skills. Station 1: draw a picture of you and a friend sharing. Station 2: practice whole-body listening with a partner for 30 seconds. Station 3: act out Stop-Talk-Solve with a puppet scenario card. Station 4: write or draw an "invitation" to give to someone this week. After the relay, students make a friendship bracelet (simple yarn braid) for another group member and tell them one thing they like about them.',
        closing_checkout: 'Certificate ceremony with friendship bracelets. Each student completes the sentence: "The most important thing I learned about being a friend is ___." Group photo for the counselor\'s bulletin board.',
        take_home_challenge: 'Keep being the kind of friend you\'d want to have. If a friendship problem comes up, remember: Stop, Talk, Solve!',
      },
    ],
  },

  // ── Kit 3: Grief & Loss (6 sessions, grades K-5) ──
  {
    id: 'kit-grief',
    title: 'Grief & Loss',
    description: 'A 6-session group for students who have experienced the death of a loved one, pet, or significant loss (including divorce, moving, or incarceration of a parent). Students learn that grief is normal, share memories, and build coping strategies in a safe space.',
    grade_range: 'K-5',
    session_count: 6,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'Introducing Our Group',
        objective: 'Students will learn they are not alone in experiencing loss, establish group rules, and begin building trust.',
        opening_activity: 'Counselor opens with: "Everyone in this group has something in common — you\'ve all lost someone or something very important to you. This group is a safe place to talk about it, remember, and feel better." Establish group rules together: what\'s shared here stays here, be kind, it\'s OK to cry, you can pass if you don\'t want to share.',
        main_activity: 'Each student decorates a paper bag as their "Memory Bag." On the outside, they write their name and draw things that represent them now (favorite color, hobby, pet). This is their container for the group — they\'ll add things each week. Then go around the circle: each student shares who or what they lost and one word about how they feel about it today. Counselor normalizes all responses: "Sad, angry, confused, fine — all of those are OK."',
        closing_checkout: 'Read "The Invisible String" by Patrice Karst. Key message: love connects us to people even when they\'re gone. Students hold a piece of yarn to symbolize their invisible string.',
        take_home_challenge: 'Bring one small item or photo that reminds you of the person or thing you lost. We\'ll share these next time.',
      },
      {
        session_number: 2,
        title: 'Sharing Memories',
        objective: 'Students will share a positive memory of their loved one and understand that remembering is a healthy part of grief.',
        opening_activity: 'Feelings check-in using feeling faces cards. Each student picks the face that matches their mood and says one sentence about why.',
        main_activity: 'Students share the item or photo they brought (or describe a memory if they didn\'t bring something). Counselor models first: "I brought this picture of my grandmother. She used to make the best pancakes on Saturday mornings. When I look at this picture, I feel happy and a little sad at the same time — and that\'s OK." After each student shares, the group responds with "Thank you for sharing that with us." Then students draw their favorite memory on a card and place it in their Memory Bag.',
        closing_checkout: 'Counselor says: "Our memories are gifts. They help us keep the people we love close to our hearts, even when they\'re not here." Students say one word about how they feel after sharing.',
        take_home_challenge: 'Ask a family member to tell you their favorite memory of the person you lost. Listen carefully and hold onto that story.',
      },
      {
        session_number: 3,
        title: 'The Many Faces of Grief',
        objective: 'Students will identify the wide range of emotions in grief and understand that all feelings are normal and that grief is not linear.',
        opening_activity: 'Play "Feelings Bingo" — counselor reads a feeling (angry, guilty, relieved, scared, lonely, numb, happy) and students mark their card if they\'ve felt that way about their loss. No winners or losers — just noticing.',
        main_activity: 'Introduce the idea that grief is like a ball bouncing around inside a box. Sometimes it hits the "sadness" wall, sometimes the "anger" wall, sometimes the "happy memory" wall. It bounces around unpredictably. Students make a "Grief Ball Box" — decorate a small box, write different feelings on the inside walls, and put a bouncy ball or marble inside. Shake it and see which wall it lands on. "That\'s how grief works — you never know which feeling will show up, and that\'s normal."',
        closing_checkout: 'Each student names one feeling they\'ve had about their loss that surprised them. Counselor reinforces: "There is no wrong way to grieve."',
        take_home_challenge: 'When a grief feeling pops up this week, name it instead of pushing it away. Say to yourself, "I\'m feeling ___ and that\'s OK."',
      },
      {
        session_number: 4,
        title: 'Coping with Hard Days',
        objective: 'Students will identify coping strategies for difficult grief moments such as holidays, birthdays, and unexpected triggers.',
        opening_activity: 'Ask: "Are there certain days or times when missing your person feels extra hard?" (Holidays, their birthday, bedtime, their empty seat at dinner.) Normalize that these moments happen and can catch you off guard.',
        main_activity: 'Create a "Coping Toolbox" card with 6 strategies: (1) Talk to a safe adult about how you feel. (2) Draw or write about your person. (3) Do something your person loved — cook their recipe, play their favorite game. (4) Use breathing or mindfulness when feelings get big. (5) Look at photos or hold something that reminds you of them. (6) Cry if you need to — tears are not weakness. Students pick their top 3 and write them on a card for their Memory Bag. Then practice the breathing strategy together: 4 counts in, hold for 4, out for 6.',
        closing_checkout: 'Students share which coping strategy they think will help them most. "Mine is talking to my mom" or "Mine is drawing pictures of my dog."',
        take_home_challenge: 'Try one coping strategy this week when a hard moment comes. Put a check mark on your card when you use it.',
      },
      {
        session_number: 5,
        title: 'Writing a Letter',
        objective: 'Students will process unfinished feelings by writing or drawing a letter to the person they lost.',
        opening_activity: 'Coping check-in: who used a strategy from their toolbox? What happened?',
        main_activity: 'Counselor models writing a short letter: "Dear Grandma, I miss you so much. I wish you could see how tall I\'ve gotten. I still think about your pancakes every Saturday. There are some things I wish I could have told you — like thank you for always reading to me. I love you and I carry you with me." Students write their own letter (younger students can draw a picture with dictated sentences). They can say anything: I miss you, I\'m sorry, I\'m angry, I love you, I wish you could see me now, I have a question for you. Letters go in the Memory Bag. Counselor emphasizes: this letter is for YOU. You don\'t have to share it.',
        closing_checkout: 'Students who want to share may read part of their letter. The group responds with "Thank you." Those who want to keep it private hold it to their heart instead.',
        take_home_challenge: 'If there\'s anything else you want to say to your person, add to your letter this week. Or write a new one whenever you need to.',
      },
      {
        session_number: 6,
        title: 'Carrying Love Forward',
        objective: 'Students will identify how they want to honor their loved one\'s memory and recognize their own strength and growth.',
        opening_activity: 'Review the journey: Session 1 we introduced ourselves, Session 2 we shared memories, Session 3 we learned about feelings, Session 4 we built coping tools, Session 5 we wrote letters. "Look how brave you\'ve been."',
        main_activity: 'Each student creates a "Love Legacy" — one way they will carry their person\'s love forward. Maybe grandpa loved fishing, so you\'ll learn about fish. Maybe your friend was always kind, so you\'ll do an extra kind thing each week. Students write or draw their Love Legacy on a heart-shaped card. Then the group makes a collaborative mural: each student paints or draws their person in a sky full of stars. Title: "Always in Our Hearts." Display in the counselor\'s office.',
        closing_checkout: 'Certificate ceremony. Each student completes: "One thing I\'ve learned from this group is ___." Counselor reminds them: "This group is ending, but my door is ALWAYS open. Grief doesn\'t have a deadline, and you can come talk to me anytime." Group hug or hand-squeeze circle.',
        take_home_challenge: 'Take your Memory Bag home. Keep adding to it whenever you want. Your memories and your love will last forever.',
      },
    ],
  },

  // ── Kit 4: Anxiety & Worry (6 sessions, grades 2-5) ──
  {
    id: 'kit-anxiety',
    title: 'Anxiety & Worry',
    description: 'A 6-session group teaching students to understand anxiety, challenge worried thoughts, and build a personal calm-down plan. Students learn that worry is normal but manageable, and that they are braver than they think.',
    grade_range: '2-5',
    session_count: 6,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'Meet Your Worry Brain',
        objective: 'Students will define anxiety, normalize worry as something everyone experiences, and identify their own worry patterns.',
        opening_activity: 'Anonymous worry drop: each student writes one thing they worry about on a slip of paper (no names). Counselor reads them aloud. "Look at how many of us worry about similar things. You are NOT alone."',
        main_activity: 'Introduce the "Worry Brain" — the part of your brain (amygdala) whose job is to keep you safe. It\'s like a smoke alarm: sometimes it goes off for real smoke (actual danger), but sometimes it goes off when you\'re just making toast (false alarm). Anxiety is when your smoke alarm goes off too much. Students draw their own "Worry Brain" character — give it a name, a face, and a voice. "What does YOUR worry brain say to you?" (You\'re going to mess up. Everyone is looking at you. Something bad will happen.) Share in pairs.',
        closing_checkout: 'Each student introduces their Worry Brain character to the group. Counselor says: "Now that we know its name, we can start talking back to it."',
        take_home_challenge: 'This week, when you notice your worry brain talking, say to yourself: "There goes ___ (character name) again. Is this real smoke or just toast?" Write down one example.',
      },
      {
        session_number: 2,
        title: 'What Worry Does to My Body',
        objective: 'Students will identify the physical symptoms of anxiety and practice recognizing them as signals, not emergencies.',
        opening_activity: 'Worry Brain report: who noticed their worry brain this week? Was it real smoke or toast?',
        main_activity: 'Give each student a body outline worksheet. Counselor describes common anxiety symptoms: stomach ache, headache, fast heartbeat, sweaty palms, tight chest, shaky legs, can\'t breathe, feeling dizzy. Students color or mark where THEY feel anxiety in their body. Then discuss: "Your body is not broken — it\'s doing what it\'s supposed to do when it thinks there\'s danger. The problem is, your body can\'t tell the difference between a bear chasing you and a math test." Teach one quick calming strategy: 5-finger breathing (trace up and down each finger while breathing in and out). Practice 3 times together.',
        closing_checkout: 'Each student names their number-one body symptom. "When I feel ___ in my ___, I know my worry brain is activated."',
        take_home_challenge: 'When you feel a worry symptom this week, try 5-finger breathing right away. Track how many times you use it.',
      },
      {
        session_number: 3,
        title: 'Thought Traps',
        objective: 'Students will identify common thinking errors (catastrophizing, mind-reading, fortune-telling) and practice challenging them.',
        opening_activity: 'Breathing check: who used 5-finger breathing? Did it help? How many times did you try it?',
        main_activity: 'Introduce 3 "Thought Traps" — sneaky ways our worry brain tricks us. Trap 1: Catastrophizing ("The worst thing EVER will happen!"). Trap 2: Mind-Reading ("Everyone thinks I\'m weird."). Trap 3: Fortune-Telling ("I just KNOW I\'m going to fail."). For each trap, read a kid-friendly example and ask: "Is this thought a FACT or a FEELING?" Then teach the "Talk Back" technique: ask yourself (1) What\'s the evidence? (2) Has this actually happened before? (3) What would I tell my friend if they had this thought? Students practice with 6 worry statements on cards, identifying the trap and writing a Talk Back response.',
        closing_checkout: 'Each student shares their favorite Talk Back response. "I told my worry brain: the evidence says I actually do OK on most tests."',
        take_home_challenge: 'Catch one Thought Trap this week. Write down the worry, name the trap, and write your Talk Back.',
      },
      {
        session_number: 4,
        title: 'The Worry Ladder',
        objective: 'Students will understand that avoiding fears makes anxiety worse and that facing fears in small steps makes them smaller.',
        opening_activity: 'Thought Trap share: who caught a trap? What was the Talk Back? Celebrate the effort.',
        main_activity: 'Introduce the Worry Ladder (exposure concept in kid-friendly terms). "When you avoid something scary, your worry brain thinks: See! I was right! It WAS dangerous! And the fear grows. But when you take small brave steps toward the fear, your worry brain learns: Oh, this is actually OK." Draw a ladder on the board. Put the scariest version of a common fear at the top (giving a speech in front of the whole school) and the easiest brave step at the bottom (reading aloud to the counselor). Fill in the middle rungs together. Each student then creates their own Worry Ladder for ONE thing they avoid. Bottom rung = easiest step they could take this week.',
        closing_checkout: 'Students share their bottom rung brave step. Group cheers them on: "You can do it!"',
        take_home_challenge: 'Try your bottom rung this week. Just one small brave step. Report back next time — we want to celebrate with you.',
      },
      {
        session_number: 5,
        title: 'Building My Calm-Down Kit',
        objective: 'Students will compile a personalized anxiety management toolkit combining body strategies, thinking strategies, and brave steps.',
        opening_activity: 'Brave step reports! Did anyone try their bottom rung? What happened? How did you feel after?',
        main_activity: 'Students create a "Calm-Down Kit" card (folds into a pocket-sized booklet). Page 1: My Worry Brain\'s name and what it usually says. Page 2: My body signals (from Session 2). Page 3: My 3 best calming strategies — choose from 5-finger breathing, counting backwards from 10, progressive muscle relaxation, positive self-talk, or grounding (5 things I see, 4 I hear, 3 I touch, 2 I smell, 1 I taste). Page 4: My Talk Back phrase (from Session 3). Page 5: My next brave step on my Worry Ladder (from Session 4). Page 6: My safe adults I can talk to (list 3 names). Counselor demonstrates the full sequence: "I notice my heart racing. That\'s my worry brain. I\'m going to do 5-finger breathing. Now I\'ll Talk Back: the evidence says I\'ll be fine. And my brave step this week is ___."',
        closing_checkout: 'Each student walks through their kit out loud: "When I worry, I notice ___, I calm down with ___, I Talk Back by saying ___, and I can talk to ___."',
        take_home_challenge: 'Keep your Calm-Down Kit in your desk or backpack. Use it at least once before our final session. Try the next rung on your Worry Ladder if you\'re ready.',
      },
      {
        session_number: 6,
        title: 'Brave, Not Perfect',
        objective: 'Students will celebrate their growth, reinforce strategies, and commit to ongoing brave steps.',
        opening_activity: 'Each student shares one way they\'ve handled worry differently since the group started. Counselor has specific observations ready: "I noticed that you raised your hand in class last week — that was your brave step!"',
        main_activity: 'Play "Worry Boss" — counselor reads 6 new worry scenarios. For each one, students use their Calm-Down Kit to walk through their full response. The group votes on the best Talk Back for each scenario. Then students write a letter to their worry brain: "Dear ___, I know you\'re trying to protect me, but I don\'t need you to be so loud anymore. I have strategies now. I can be brave AND scared at the same time. Signed, ___." Finally, students design a "Bravery Badge" — a small card with a picture or symbol that represents their courage.',
        closing_checkout: 'Certificate ceremony. Each student completes: "The bravest thing I did in this group was ___." Final mantra together: "Being brave doesn\'t mean you\'re not scared. It means you do it anyway." Group high-five.',
        take_home_challenge: 'Keep climbing your Worry Ladder, one rung at a time. And remember: your counselor\'s door is always open when your worry brain gets too loud.',
      },
    ],
  },

  // ── Kit 5: Self-Esteem (6 sessions, grades 2-5) ──
  {
    id: 'kit-self-esteem',
    title: 'Self-Esteem',
    description: 'A 6-session group helping students build a positive self-image, recognize their strengths, challenge negative self-talk, and develop confidence. Students learn that their worth is not determined by grades, appearance, or what others think.',
    grade_range: '2-5',
    session_count: 6,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'What Is Self-Esteem?',
        objective: 'Students will define self-esteem and assess their own level of self-confidence in a safe environment.',
        opening_activity: 'Rating scale: students hold up 1-5 fingers for "How much do you like being you?" No judgment — just noticing. Counselor shares: "By the end of this group, I want that number to go up for all of us."',
        main_activity: 'Define self-esteem as "how you feel about yourself — your belief that you are valuable, capable, and worthy of good things." It\'s like a bank account: kind self-talk and accomplishments make deposits, and negative self-talk and criticism make withdrawals. Students make a Self-Esteem Bank Account. On the left column (deposits), they write 5 things that make them feel good about themselves. On the right column (withdrawals), they write things that make them feel bad about themselves. Discuss: which column is longer? Which column do you focus on more?',
        closing_checkout: 'Each student shares one item from their "deposits" column. Group responds to each one: "That IS something to feel good about!"',
        take_home_challenge: 'Every night this week, think of one "deposit" to add to your self-esteem bank. Write it down or tell a family member.',
      },
      {
        session_number: 2,
        title: 'My Strengths and Superpowers',
        objective: 'Students will identify personal strengths across multiple areas (academic, social, creative, physical, character) and see themselves as multi-dimensional.',
        opening_activity: 'Deposit check: how many deposits did you make this week? Share your favorite one.',
        main_activity: 'Give each student a large star template with 5 points. Each point represents a different type of strength: (1) School smarts — what I\'m good at in class. (2) Friend smarts — how I\'m a good friend. (3) Creative smarts — how I express myself (art, music, building, writing). (4) Body smarts — what my body can do (sports, dance, climbing, swimming). (5) Heart smarts — character qualities (kind, honest, brave, funny, patient). Students fill in each point with at least one strength. If a student is stuck, other group members can suggest strengths they\'ve noticed. Counselor emphasizes: "You don\'t have to be the BEST at something for it to be a strength. Being good at being kind is just as important as being good at math."',
        closing_checkout: 'Students hold up their star and read all 5 strengths out loud. "I am smart at ___, I am a good friend because ___, I am creative at ___..."',
        take_home_challenge: 'Ask a family member or friend: "What do you think I\'m good at?" Add their answer to your star.',
      },
      {
        session_number: 3,
        title: 'The Negative Self-Talk Monster',
        objective: 'Students will recognize negative self-talk patterns and understand how they damage self-esteem.',
        opening_activity: 'Share what your family member said about your strengths. How did it feel to hear that?',
        main_activity: 'Introduce the "Negative Self-Talk Monster" — that voice in your head that says mean things about you. "Would you say those things to your best friend? Then why do you say them to yourself?" Students draw their monster and write the things it says in speech bubbles: "You\'re stupid," "Nobody likes you," "You can\'t do anything right," "You\'re ugly." Then discuss: Where do these messages come from? (Comparing ourselves to others, social media, being teased, past failures.) Key insight: just because your monster says it doesn\'t make it TRUE. Feelings are real, but they\'re not always facts.',
        closing_checkout: 'Each student rips one speech bubble off their monster and throws it in the trash. "That thought is not a fact, and I\'m throwing it away."',
        take_home_challenge: 'Catch your Negative Self-Talk Monster this week. When it says something mean, write it down. Next week we\'ll learn to fight back.',
      },
      {
        session_number: 4,
        title: 'Talking Back to the Monster',
        objective: 'Students will replace negative self-talk with positive affirmations and realistic self-statements.',
        opening_activity: 'Monster report: what did your Negative Self-Talk Monster say this week? Let\'s write those thoughts on the board so we can fight them.',
        main_activity: 'For each negative thought on the board, the group creates a "Power Phrase" — a true, kind statement to replace it. "I\'m stupid" becomes "I\'m still learning, and that\'s OK." "Nobody likes me" becomes "I have people who care about me." "I can\'t do anything right" becomes "I make mistakes sometimes, and that just means I\'m trying." Students create Power Phrase cards — 5 positive statements they can carry with them. Then practice the Mirror Challenge: look in a small mirror and say one Power Phrase out loud with conviction. Counselor models first. It feels awkward — that\'s normal. Do it anyway.',
        closing_checkout: 'Each student says their favorite Power Phrase to the whole group. The group echoes it back to them.',
        take_home_challenge: 'Say your Power Phrase in the mirror every morning this week. Yes, it will feel silly. Do it anyway. Your brain needs to hear the truth.',
      },
      {
        session_number: 5,
        title: 'Mistakes Are Proof I\'m Trying',
        objective: 'Students will develop a growth mindset toward mistakes and reduce perfectionism.',
        opening_activity: 'Mirror challenge check: who did it? How many days? How did it feel by the end of the week?',
        main_activity: 'Tell the stories of 3 famous "failures": Walt Disney was fired for "lacking imagination." Michael Jordan was cut from his high school basketball team. J.K. Rowling\'s Harry Potter was rejected by 12 publishers. "What if they had given up?" Discuss: what\'s the difference between failing and BEING a failure? (Failing is something that happens. Being a failure is a lie your monster tells you.) Students make a "Mistake Resume" — a list of 3 mistakes they\'ve made and what they learned from each one. Then rewrite each mistake as a success story: "I failed my spelling test, but I asked for help and got a B the next time."',
        closing_checkout: 'Students share one mistake they\'re actually grateful for now because of what they learned.',
        take_home_challenge: 'When you make a mistake this week, instead of beating yourself up, say: "That was tough, but I\'m learning." Write down what you learned from it.',
      },
      {
        session_number: 6,
        title: 'I Am Enough',
        objective: 'Students will celebrate their worth, recognize their growth, and commit to ongoing self-compassion.',
        opening_activity: 'Self-esteem re-check: hold up 1-5 fingers for "How much do you like being you?" Compare to Session 1. Celebrate any growth!',
        main_activity: 'Compliment Circle: each student sits in the center while every other group member says one genuine thing they admire about them. Counselor goes first to model specific compliments ("I admire how you always check on people who seem sad" rather than "you\'re nice"). Then students create an "I Am" poem using this template: "I am (2 strengths). I wonder (something curious about me). I hear (my Power Phrase). I see (my future self). I am (repeat line 1)." Share poems aloud. Finally, counselor distributes small pocket mirrors with a sticky note on each that says "I Am Enough." This is their reminder.',
        closing_checkout: 'Certificate ceremony. Students complete: "One thing I know about myself now that I didn\'t know 6 weeks ago is ___." Final group cheer: "I am strong! I am smart! I am kind! I am ENOUGH!"',
        take_home_challenge: 'Keep your mirror, your Power Phrases, and your star. Look at them when your Negative Self-Talk Monster shows up. And remember: the counselor\'s door is always open.',
      },
    ],
  },

  // ── Kit 6: Family Changes (6 sessions, grades K-5) ──
  {
    id: 'kit-family-changes',
    title: 'Family Changes',
    description: 'A 6-session group for students dealing with family transitions including divorce, separation, remarriage, deployment, incarceration, or a parent moving away. Students learn that family changes are not their fault, feelings about change are normal, and they can adapt and thrive.',
    grade_range: 'K-5',
    session_count: 6,
    asca_domain: 'social-emotional',
    sessions: [
      {
        session_number: 1,
        title: 'Families Come in All Shapes',
        objective: 'Students will understand that families look different and that changes in family structure do not change their worth or lovability.',
        opening_activity: 'Counselor draws 6 different family structures on the board: two-parent, single-parent, blended/step, grandparent-led, two-mom or two-dad, foster family. "All of these are REAL families. A family is the people who love and take care of you."',
        main_activity: 'Students draw their family — whoever lives in their home or whoever they consider family. Younger students draw and dictate; older students draw and label. Then each student shares their picture. Counselor points out that families change: a new baby, someone moves away, divorce, a grandparent moves in. "Has YOUR family changed?" Students share as much as they\'re comfortable with. Establish the group norm: this is a safe space. No one will judge your family. Key message: "Your family changing is NOT your fault."',
        closing_checkout: 'Each student says one thing they love about their family, no matter what it looks like right now.',
        take_home_challenge: 'Draw a picture of your family doing something fun together. Bring it to our next session.',
      },
      {
        session_number: 2,
        title: 'It\'s Not My Fault',
        objective: 'Students will understand that family changes (especially divorce) are adult decisions and are never the child\'s fault.',
        opening_activity: 'Family picture share: volunteers show their drawing and tell about the fun memory.',
        main_activity: 'Read "Dinosaurs Divorce" by Laurene Krasny Brown (or summarize key points for older students). Then address the biggest myth directly: "Some kids think their parents\' divorce or family change happened because of something THEY did. Maybe you think: if I had been better behaved, they\'d still be together. Or: if I hadn\'t asked for so much, they wouldn\'t fight." Pause. "That is NOT true. Family changes are grown-up decisions about grown-up problems. Kids do not cause them. Kids cannot fix them." Students write one worry or guilty thought they\'ve had on a slip of paper. Counselor reads them anonymously and the group responds to each one: "Not your fault." Slips go in a "Let It Go" box.',
        closing_checkout: 'Students say together: "It\'s not my fault. I am loved. My feelings matter."',
        take_home_challenge: 'If the "my fault" thought comes up this week, say the group phrase to yourself: "It\'s not my fault. I am loved."',
      },
      {
        session_number: 3,
        title: 'A Tornado of Feelings',
        objective: 'Students will identify and express the complex emotions that come with family changes, including contradictory feelings.',
        opening_activity: 'Counselor shows a picture of a tornado. "Family changes can feel like a tornado of feelings — everything spinning around at once, and you can\'t tell which feeling is which."',
        main_activity: 'Give each student a paper plate divided into 6 sections like a pie chart. Each section represents a feeling they might have about their family change: sad, angry, scared, confused, relieved, hopeful. Students color each section bigger or smaller based on how much of that feeling they have. Discuss: "Is it OK to feel relieved AND sad at the same time? YES. Is it OK to feel angry at someone you love? YES. Can you feel happy at one parent\'s house and sad at the other? YES." Normalize the contradiction. Then students pick their biggest feeling and draw a picture of a time they felt that way. Share in small groups.',
        closing_checkout: 'Students name the feeling that surprised them most on their pie chart. "I didn\'t expect to feel ___ about my family change."',
        take_home_challenge: 'When a big feeling hits this week, name it. Just say: "I\'m feeling ___ right now, and that\'s OK." Tell a safe adult about it.',
      },
      {
        session_number: 4,
        title: 'Two Homes, One Me',
        objective: 'Students will develop strategies for navigating life in two homes (or other logistical challenges of family change) and identify what stays the same.',
        opening_activity: 'Feelings check-in: "What zone are you in today?" (Blue, Green, Yellow, Red). Brief shares about what\'s been hard or good this week.',
        main_activity: 'Create a "Things That Stay the Same" anchor chart. Even when families change, many things stay the same: your name, your school, your friends, your teacher, your talents, your counselor, people who love you. Students add their own: my dog, my soccer team, my best friend. Then address the practical hard parts: forgetting things at the other house, different rules at different homes, missing one parent when you\'re with the other, holidays being different. Students brainstorm solutions together: a packing checklist, a "transition backpack" with must-haves, a special goodnight call or text. Counselor validates: "These things ARE hard. It\'s OK to say so."',
        closing_checkout: 'Each student names one thing that stays the same that they\'re grateful for.',
        take_home_challenge: 'Make a short list of "must-haves" for your backpack or overnight bag. Having your important things with you can help transitions feel easier.',
      },
      {
        session_number: 5,
        title: 'Using My Voice',
        objective: 'Students will practice communicating their feelings and needs to family members and identify trusted adults they can talk to.',
        opening_activity: 'Must-haves check: did anyone try the transition backpack idea? What did you put in it?',
        main_activity: 'Sometimes kids feel like they can\'t say anything about the family change because they don\'t want to make their parents sadder or angrier. But your feelings MATTER and your voice COUNTS. Teach kid-friendly sentence starters: "I feel ___ when ___." "I need ___." "Can I ask you something?" "It helps me when ___." Role-play 4 scenarios: (1) telling a parent you miss the other parent without hurting their feelings, (2) asking for something comforting during transitions, (3) telling a parent you need quiet time, (4) asking a teacher for patience on a hard day. Students practice in pairs. Then make a "Safe Adults Map" — draw or write 3-5 people they trust enough to talk to about their family changes.',
        closing_checkout: 'Students share one sentence they want to say to someone and who they want to say it to. "I want to tell my mom that I need a hug before she leaves for work."',
        take_home_challenge: 'Use one of your sentence starters with a safe adult this week. Your voice matters.',
      },
      {
        session_number: 6,
        title: 'Strong, Flexible, and Growing',
        objective: 'Students will recognize their resilience, celebrate their coping skills, and commit to asking for help when needed.',
        opening_activity: 'Voice check: did anyone use a sentence starter? What happened? How did it feel?',
        main_activity: 'Show a picture of a tree in a strong wind — it bends but doesn\'t break. "That tree is like YOU. Family changes are a strong wind. You\'ve bent, but you didn\'t break. And look — you\'re still growing." Students create a "My Strong Tree" drawing. Roots = things that keep me grounded (family, friends, faith, school, hobbies). Trunk = my strengths (from our earlier sessions). Branches = things I\'m growing toward (goals, hopes, dreams). Leaves = people who support me. Then the group writes a collaborative poem: each student contributes one line starting with "Even though my family changed, I still..." (am loved, have friends, can laugh, am learning, have hope). Counselor reads the full poem aloud.',
        closing_checkout: 'Certificate ceremony. Students complete: "The most important thing I learned is ___." Counselor reminds them: "Change is hard, but you are harder. And my door is always, always open." Group puts hands in the center: "Strong, flexible, and growing — GO!"',
        take_home_challenge: 'Hang your Strong Tree somewhere you\'ll see it. When the wind blows hard, look at your roots and remember: you will not break.',
      },
    ],
  },
];
