/**
 * Visual resources for elementary school counselors (K-5).
 * Each resource includes metadata and a generatePdf function using jsPDF.
 */

export const VISUAL_RESOURCES = [
  // ── 1. Feelings Thermometer ──
  {
    id: 'vis-1',
    title: 'Feelings Thermometer',
    description: 'A vertical scale from 1 to 5 with gradient colors and emotion words at each level. Includes a "My Name" field for students to personalize.',
    type: 'worksheet',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'letter');
      const pw = 216;

      // Title
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text('Feelings Thermometer', pw / 2, 28, { align: 'center' });

      // Name field
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text('My Name: ______________________________', pw / 2, 42, { align: 'center' });

      // Thermometer data (bottom to top)
      const levels = [
        { num: 1, label: 'Calm & Relaxed', words: 'Peaceful, Content, Comfortable', color: [59, 130, 246] },   // blue
        { num: 2, label: 'Okay', words: 'Fine, Focused, Ready to Learn', color: [34, 197, 94] },               // green
        { num: 3, label: 'Getting Upset', words: 'Frustrated, Annoyed, Nervous', color: [234, 179, 8] },       // yellow
        { num: 4, label: 'Very Upset', words: 'Angry, Anxious, Overwhelmed', color: [249, 115, 22] },          // orange
        { num: 5, label: 'Out of Control', words: 'Furious, Terrified, Meltdown', color: [239, 68, 68] },      // red
      ];

      const thermX = 55;
      const thermW = 40;
      const segH = 32;
      const startY = 62;

      // Draw thermometer segments (top = 5, bottom = 1)
      for (let i = 0; i < levels.length; i++) {
        const lvl = levels[4 - i]; // reverse so 5 is at top
        const y = startY + i * segH;

        // Colored rectangle
        doc.setFillColor(...lvl.color);
        doc.setDrawColor(60, 60, 60);
        doc.setLineWidth(0.5);
        doc.roundedRect(thermX, y, thermW, segH, 2, 2, 'FD');

        // Number inside
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(String(lvl.num), thermX + thermW / 2, y + segH / 2 + 3, { align: 'center' });

        // Label to the right
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...lvl.color);
        doc.text(lvl.label, thermX + thermW + 10, y + 12);

        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);
        doc.text(lvl.words, thermX + thermW + 10, y + 22);
      }

      // Instruction box
      const boxY = startY + 5 * segH + 12;
      doc.setFillColor(245, 245, 245);
      doc.roundedRect(20, boxY, pw - 40, 30, 3, 3, 'F');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text('How to use:', 28, boxY + 10);
      doc.setFont('helvetica', 'normal');
      doc.text('Point to the number that matches how you feel right now.', 28, boxY + 18);
      doc.text('Tell your counselor or teacher what you need to get back to a 1 or 2.', 28, boxY + 25);

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 272, { align: 'center' });

      return doc;
    },
  },

  // ── 2. Coping Strategies Wheel ──
  {
    id: 'vis-2',
    title: 'Coping Strategies Wheel',
    description: 'A visual grid of 12 coping strategies students can use when feeling upset, angry, or anxious. Each strategy has a clear label in a colorful tile.',
    type: 'poster',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('landscape', 'mm', 'letter');
      const pw = 279;
      const ph = 216;

      // Title
      doc.setFontSize(30);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text('My Coping Strategies', pw / 2, 25, { align: 'center' });
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text('When I feel upset, I can try...', pw / 2, 35, { align: 'center' });

      const strategies = [
        { text: 'Take Deep\nBreaths', color: [59, 130, 246] },
        { text: 'Count\nto 10', color: [34, 197, 94] },
        { text: 'Draw How\nI Feel', color: [168, 85, 247] },
        { text: 'Talk to a\nSafe Adult', color: [249, 115, 22] },
        { text: 'Squeeze a\nStress Ball', color: [236, 72, 153] },
        { text: 'Go to My\nCalm Spot', color: [20, 184, 166] },
        { text: 'Write in\nMy Journal', color: [234, 179, 8] },
        { text: 'Listen\nto Music', color: [99, 102, 241] },
        { text: 'Get a Drink\nof Water', color: [6, 182, 212] },
        { text: 'Do Jumping\nJacks', color: [239, 68, 68] },
        { text: 'Think of My\nHappy Place', color: [16, 185, 129] },
        { text: 'Read\na Book', color: [245, 158, 11] },
      ];

      const cols = 4;
      const rows = 3;
      const tileW = 55;
      const tileH = 45;
      const gapX = 8;
      const gapY = 8;
      const gridW = cols * tileW + (cols - 1) * gapX;
      const gridH = rows * tileH + (rows - 1) * gapY;
      const offsetX = (pw - gridW) / 2;
      const offsetY = 48;

      for (let i = 0; i < strategies.length; i++) {
        const col = i % cols;
        const row = Math.floor(i / cols);
        const x = offsetX + col * (tileW + gapX);
        const y = offsetY + row * (tileH + gapY);
        const s = strategies[i];

        // Tile background
        doc.setFillColor(...s.color);
        doc.roundedRect(x, y, tileW, tileH, 5, 5, 'F');

        // Strategy text
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        const lines = s.text.split('\n');
        const lineH = 7;
        const textStartY = y + (tileH - lines.length * lineH) / 2 + lineH;
        lines.forEach((line, li) => {
          doc.text(line, x + tileW / 2, textStartY + li * lineH, { align: 'center' });
        });
      }

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, ph - 10, { align: 'center' });

      return doc;
    },
  },

  // ── 3. Problem-Solving Steps Poster ──
  {
    id: 'vis-3',
    title: 'Problem-Solving Steps Poster',
    description: 'A STOP (red) / THINK (yellow) / ACT (green) traffic light poster with descriptions of what to do at each step.',
    type: 'poster',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'letter');
      const pw = 216;

      // Title
      doc.setFontSize(32);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text('Problem-Solving Steps', pw / 2, 28, { align: 'center' });

      const steps = [
        {
          label: 'STOP',
          color: [239, 68, 68],
          icon: 'X',
          heading: 'Pause before you react.',
          bullets: [
            'Take a deep breath.',
            'Don\'t say or do anything yet.',
            'Feel your feet on the floor.',
            'Count to 5 in your head.',
          ],
        },
        {
          label: 'THINK',
          color: [234, 179, 8],
          icon: '?',
          heading: 'Consider your options.',
          bullets: [
            'What happened? What\'s the problem?',
            'What are my choices?',
            'What might happen with each choice?',
            'Which choice is safe, fair, and kind?',
          ],
        },
        {
          label: 'ACT',
          color: [34, 197, 94],
          icon: '!',
          heading: 'Choose the best option and try it.',
          bullets: [
            'Do your best choice.',
            'Use a calm voice.',
            'If it doesn\'t work, go back to THINK.',
            'Ask for help if you need it.',
          ],
        },
      ];

      const blockH = 60;
      const blockW = pw - 40;
      const startY = 45;

      steps.forEach((step, i) => {
        const y = startY + i * (blockH + 12);

        // Background rectangle
        doc.setFillColor(...step.color);
        doc.roundedRect(20, y, blockW, blockH, 6, 6, 'F');

        // Step label (large)
        doc.setFontSize(36);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(step.label, 35, y + 25);

        // Heading
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(step.heading, 35, y + 37);

        // Bullets
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        const bulletStartX = 40;
        step.bullets.forEach((b, bi) => {
          const bx = bi < 2 ? bulletStartX : bulletStartX + blockW / 2 - 10;
          const by = y + 46 + (bi % 2) * 7;
          doc.text('\u2022 ' + b, bx, by);
        });
      });

      // Bottom reminder
      const remY = startY + 3 * (blockH + 12) + 5;
      doc.setFillColor(240, 240, 240);
      doc.roundedRect(20, remY, blockW, 22, 3, 3, 'F');
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Remember: You always have choices. Choosing to STOP gives you power.', pw / 2, remY + 13, { align: 'center' });

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 272, { align: 'center' });

      return doc;
    },
  },

  // ── 4. Zones Reference Chart ──
  {
    id: 'vis-4',
    title: 'Zones Reference Chart',
    description: 'A four-zone reference chart (Blue, Green, Yellow, Red) showing emotions and strategies for each zone. Color-coded for quick visual identification.',
    type: 'poster',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('landscape', 'mm', 'letter');
      const pw = 279;
      const ph = 216;

      // Title
      doc.setFontSize(30);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text('Zones Reference Chart', pw / 2, 22, { align: 'center' });
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text('All zones are OK. The goal is to recognize your zone and know what to do.', pw / 2, 32, { align: 'center' });

      const zones = [
        {
          name: 'Blue Zone',
          color: [59, 130, 246],
          subtitle: 'Low Energy',
          emotions: ['Sad', 'Tired', 'Bored', 'Sick', 'Lonely', 'Shut down'],
          strategies: ['Talk to someone', 'Get a drink of water', 'Take a short walk', 'Think of something that makes you smile', 'Ask for a break'],
        },
        {
          name: 'Green Zone',
          color: [34, 197, 94],
          subtitle: 'Ready to Learn',
          emotions: ['Calm', 'Happy', 'Focused', 'Content', 'Proud', 'Ready'],
          strategies: ['Keep doing what you\'re doing!', 'Help a friend', 'Stay in your routine', 'Notice how good this feels', 'Take a deep breath to stay here'],
        },
        {
          name: 'Yellow Zone',
          color: [234, 179, 8],
          subtitle: 'Losing Control',
          emotions: ['Frustrated', 'Anxious', 'Silly', 'Wiggly', 'Nervous', 'Excited'],
          strategies: ['Deep breathing', 'Count backwards from 10', 'Use a fidget tool', 'Ask for a break', 'Talk to your counselor'],
        },
        {
          name: 'Red Zone',
          color: [239, 68, 68],
          subtitle: 'Out of Control',
          emotions: ['Furious', 'Terrified', 'Aggressive', 'Meltdown', 'Screaming', 'Out of control'],
          strategies: ['STOP — don\'t act yet', 'Go to your calm-down spot', 'Wall push-ups', 'Squeeze and release', 'Get a safe adult NOW'],
        },
      ];

      const colW = 60;
      const colH = 148;
      const gapX = 6;
      const gridW = 4 * colW + 3 * gapX;
      const offsetX = (pw - gridW) / 2;
      const startY = 42;

      zones.forEach((zone, i) => {
        const x = offsetX + i * (colW + gapX);
        const y = startY;

        // Header
        doc.setFillColor(...zone.color);
        doc.roundedRect(x, y, colW, 28, 4, 4, 'F');
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(zone.name, x + colW / 2, y + 12, { align: 'center' });
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(zone.subtitle, x + colW / 2, y + 22, { align: 'center' });

        // Emotions section
        const eY = y + 32;
        doc.setFillColor(250, 250, 250);
        doc.roundedRect(x, eY, colW, 55, 3, 3, 'F');
        doc.setDrawColor(...zone.color);
        doc.setLineWidth(0.8);
        doc.roundedRect(x, eY, colW, 55, 3, 3, 'S');

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...zone.color);
        doc.text('I might feel:', x + 4, eY + 9);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        zone.emotions.forEach((e, ei) => {
          doc.text('\u2022 ' + e, x + 6, eY + 18 + ei * 6);
        });

        // Strategies section
        const sY = eY + 60;
        doc.setFillColor(250, 250, 250);
        doc.roundedRect(x, sY, colW, 56, 3, 3, 'F');
        doc.setDrawColor(...zone.color);
        doc.roundedRect(x, sY, colW, 56, 3, 3, 'S');

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...zone.color);
        doc.text('I can try:', x + 4, sY + 9);

        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        zone.strategies.forEach((s, si) => {
          doc.text('\u2022 ' + s, x + 6, sY + 18 + si * 7, { maxWidth: colW - 10 });
        });
      });

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, ph - 10, { align: 'center' });

      return doc;
    },
  },

  // ── 5. "I Need Help" Desk Card ──
  {
    id: 'vis-5',
    title: '"I Need Help" Desk Card',
    description: 'Two cards per page that students can place on their desk to silently signal they need to talk to someone. Includes a blank for the counselor\'s name.',
    type: 'card',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'letter');
      const pw = 216;

      function drawCard(x, y, w, h) {
        // Card border
        doc.setDrawColor(100, 100, 100);
        doc.setLineWidth(0.5);
        doc.setLineDashPattern([2, 2], 0);
        doc.rect(x, y, w, h);
        doc.setLineDashPattern([], 0);

        // Top colored bar
        doc.setFillColor(59, 130, 246);
        doc.roundedRect(x + 8, y + 8, w - 16, 18, 4, 4, 'F');

        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text('I Need to Talk to Someone', x + w / 2, y + 20, { align: 'center' });

        // Heart / message area
        doc.setFontSize(13);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);
        doc.text('Place this card on the corner of your desk', x + w / 2, y + 40, { align: 'center' });
        doc.text('when you need to talk.', x + w / 2, y + 48, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 100, 100);
        doc.text('You don\'t have to say anything out loud.', x + w / 2, y + 60, { align: 'center' });
        doc.text('Your teacher will let your counselor know.', x + w / 2, y + 68, { align: 'center' });

        // Counselor name blank
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(59, 130, 246);
        doc.text('My Counselor:', x + w / 2 - 30, y + 85);

        doc.setLineWidth(0.5);
        doc.setDrawColor(59, 130, 246);
        doc.line(x + w / 2 + 10, y + 85, x + w - 20, y + 85);

        // Reassurance message
        doc.setFillColor(240, 248, 255);
        doc.roundedRect(x + 12, y + 92, w - 24, 16, 3, 3, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(59, 130, 246);
        doc.text('You are not in trouble. Asking for help is brave.', x + w / 2, y + 102, { align: 'center' });
      }

      const cardW = pw - 30;
      const cardH = 120;

      // Card 1
      drawCard(15, 15, cardW, cardH);
      // Card 2
      drawCard(15, 15 + cardH + 10, cardW, cardH);

      // Cut line instruction
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'italic');
      doc.text('Cut along the dashed lines. Fold in half and place on desk as needed.', pw / 2, 270, { align: 'center' });

      // Footer
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 277, { align: 'center' });

      return doc;
    },
  },

  // ── 6. Safety Plan (Student) ──
  {
    id: 'vis-6',
    title: 'Safety Plan (Student)',
    description: 'A warm, student-friendly safety plan worksheet with sections for trusted people, coping strategies, safe places, emergency contacts, and counselor information.',
    type: 'worksheet',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'letter');
      const pw = 216;

      // Header bar
      doc.setFillColor(34, 197, 94);
      doc.roundedRect(15, 10, pw - 30, 22, 5, 5, 'F');
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('My Safety Plan', pw / 2, 25, { align: 'center' });

      // Name and date
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.text('Name: ___________________________________', 20, 44);
      doc.text('Date: _______________', pw - 80, 44);

      let yPos = 56;

      function drawSection(title, color, items, lineCount) {
        // Section header
        doc.setFillColor(...color);
        doc.roundedRect(20, yPos, pw - 40, 12, 3, 3, 'F');
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(title, 28, yPos + 9);
        yPos += 14;

        // Lines
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);
        for (let i = 0; i < items.length; i++) {
          doc.text(items[i], 28, yPos);
          yPos += 2;
          doc.setDrawColor(200, 200, 200);
          doc.setLineWidth(0.3);
          doc.line(28, yPos, pw - 28, yPos);
          yPos += 5;
        }
        yPos += 3;
      }

      // Section 1: People I Can Talk To
      drawSection(
        'People I Can Talk To',
        [59, 130, 246],
        [
          '1. _______________________________________________  Phone: ___________________',
          '2. _______________________________________________  Phone: ___________________',
          '3. _______________________________________________  Phone: ___________________',
        ]
      );

      // Section 2: Things I Can Do To Feel Better
      drawSection(
        'Things I Can Do to Feel Better',
        [168, 85, 247],
        [
          '1. ______________________________________________________________________________',
          '2. ______________________________________________________________________________',
          '3. ______________________________________________________________________________',
          '4. ______________________________________________________________________________',
          '5. ______________________________________________________________________________',
        ]
      );

      // Section 3: Places I Feel Safe
      drawSection(
        'Places I Feel Safe',
        [20, 184, 166],
        [
          '1. ______________________________________________________________________________',
          '2. ______________________________________________________________________________',
          '3. ______________________________________________________________________________',
        ]
      );

      // Section 4: Emergency info
      doc.setFillColor(239, 68, 68);
      doc.roundedRect(20, yPos, pw - 40, 12, 3, 3, 'F');
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('In an Emergency', 28, yPos + 9);
      yPos += 18;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.text('My Emergency Number: ________________________________________', 28, yPos);
      yPos += 10;
      doc.text('My Counselor: _______________________________________________', 28, yPos);
      yPos += 10;
      doc.text('Crisis Hotline: 988 (Suicide & Crisis Lifeline) or text HOME to 741741', 28, yPos);
      yPos += 14;

      // Warm reminder box
      doc.setFillColor(255, 251, 235);
      doc.setDrawColor(234, 179, 8);
      doc.setLineWidth(1);
      doc.roundedRect(20, yPos, pw - 40, 18, 3, 3, 'FD');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(146, 112, 0);
      doc.text('You matter. You are not alone. It is always OK to ask for help.', pw / 2, yPos + 12, { align: 'center' });

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 272, { align: 'center' });

      return doc;
    },
  },

  // ── 7. Crisis Response Quick-Reference (Counselor Only) ──
  {
    id: 'vis-7',
    title: 'Crisis Response Quick-Reference',
    description: 'FOR COUNSELOR USE ONLY. A step-by-step flowchart for handling student disclosures: assess, respond to imminent danger, document, notify, and follow up.',
    type: 'card',
    generatePdf: async function () {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'letter');
      const pw = 216;

      // Header
      doc.setFillColor(127, 29, 29);
      doc.rect(0, 0, pw, 30, 'F');
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('CRISIS RESPONSE QUICK-REFERENCE', pw / 2, 14, { align: 'center' });
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text('FOR COUNSELOR USE ONLY \u2014 CONFIDENTIAL', pw / 2, 24, { align: 'center' });

      let y = 38;
      const m = 16;
      const boxW = pw - m * 2;

      function drawStep(stepNum, title, bgColor, bullets) {
        const lineH = 4.5;
        const titleH = 7;
        const padTop = 4;
        const padBot = 3;
        const boxH = padTop + titleH + bullets.length * lineH + padBot;

        doc.setFillColor(...bgColor);
        doc.roundedRect(m, y, boxW, boxH, 3, 3, 'F');

        // Step number circle
        doc.setFillColor(255, 255, 255);
        doc.circle(m + 11, y + padTop + titleH / 2, 5, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...bgColor);
        doc.text(String(stepNum), m + 11, y + padTop + titleH / 2 + 1.5, { align: 'center' });

        // Title
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text(title, m + 21, y + padTop + 5);

        // Bullet lines
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        bullets.forEach((line, i) => {
          doc.text('\u2022 ' + line, m + 21, y + padTop + titleH + 2 + i * lineH);
        });

        y += boxH + 3;

        // Arrow between steps
        if (stepNum < 7) {
          doc.setFillColor(160, 160, 160);
          doc.triangle(pw / 2 - 2, y - 2, pw / 2 + 2, y - 2, pw / 2, y + 1, 'F');
          y += 3;
        }
      }

      drawStep(1, 'RECEIVE THE DISCLOSURE', [59, 130, 246], [
        'Listen calmly. Do not show shock or judgment.',
        'Say: "Thank you for telling me. You did the right thing."',
        'Do NOT promise to keep it a secret.',
      ]);

      drawStep(2, 'ASSESS THE SITUATION', [168, 85, 247], [
        'Is there imminent danger to the student or others?',
        'Use a screening tool if appropriate (Columbia Protocol, etc.).',
        'Trust your training \u2014 when in doubt, treat as imminent.',
      ]);

      drawStep(3, 'IF IMMINENT DANGER', [220, 38, 38], [
        'DO NOT leave the student alone. Call 911 if immediate risk to life.',
        'Contact the principal immediately.',
        'Call 988 (Suicide & Crisis Lifeline) for guidance.',
      ]);

      drawStep(4, 'IF NOT IMMINENT', [202, 138, 4], [
        'Document the disclosure in writing (facts, not interpretations).',
        'Complete a screening form. Notify the principal.',
      ]);

      drawStep(5, 'NOTIFY PARENT / GUARDIAN', [234, 88, 12], [
        'Contact parent/guardian same day (unless parent is the concern).',
        'If abuse/neglect suspected: call CPS BEFORE notifying parent.',
        'Document the notification and parent response.',
      ]);

      drawStep(6, 'CREATE A SAFETY PLAN', [22, 163, 74], [
        'Complete the safety plan with the student.',
        'Identify trusted adults, coping strategies, and safe places.',
        'Give a copy to the student and keep one in their file.',
      ]);

      drawStep(7, 'FOLLOW UP', [15, 148, 136], [
        'Check in with the student within 24 hours.',
        'Schedule ongoing follow-up (daily for first week, then as needed).',
        'Connect to outside resources if needed. Take care of yourself.',
      ]);

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 272, { align: 'center' });

      return doc;
    },
  },
];
