import { useState, useMemo, useCallback } from 'react';
import { ICEBREAKERS, SCENARIO_CARDS, MINDFULNESS_SCRIPTS } from '../lib/sessionPrompts';
import { GROUP_STARTER_KITS } from '../lib/groupStarterKits';
import { VISUAL_RESOURCES } from '../lib/visualResources';

/* ── Style constants (matches LessonsPage patterns) ── */
const card = {
  background: '#fff',
  borderRadius: 12,
  padding: 20,
  boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  border: '1px solid var(--border, #e5e7eb)',
};

const badge = (bg, color) => ({
  display: 'inline-block',
  padding: '2px 8px',
  borderRadius: 6,
  fontSize: 11,
  fontWeight: 600,
  background: bg,
  color,
});

const sectionTab = (active) => ({
  padding: '8px 18px',
  borderRadius: 8,
  border: `2px solid ${active ? '#2A9D8F' : '#d1d5db'}`,
  background: active ? '#e6f7f5' : '#fff',
  color: active ? '#2A9D8F' : '#6b7280',
  fontSize: 13,
  fontWeight: 600,
  cursor: 'pointer',
});

const topTab = (active) => ({
  padding: '10px 22px',
  borderRadius: 10,
  border: 'none',
  background: active ? '#2A9D8F' : '#f3f4f6',
  color: active ? '#fff' : '#6b7280',
  fontSize: 14,
  fontWeight: 600,
  cursor: 'pointer',
});

const expandBtn = {
  background: 'none',
  border: 'none',
  color: '#2A9D8F',
  fontSize: 13,
  fontWeight: 600,
  cursor: 'pointer',
  padding: '4px 0',
};

/* ── Grade filter logic ── */
const GRADE_FILTERS = ['All', 'K-1', '2-5', 'K-5'];

function matchesGradeFilter(itemGrade, filter) {
  if (filter === 'All') return true;
  if (filter === itemGrade) return true;
  // K-5 items show in every filter
  if (itemGrade === 'K-5') return true;
  // K-2 items show in K-1 filter (overlap)
  if (itemGrade === 'K-2' && filter === 'K-1') return true;
  // 1-5 items show in 2-5 filter (overlap)
  if (itemGrade === '1-5' && filter === '2-5') return true;
  return false;
}

/* ── PDF generation for Group Starter Kits ── */
async function printFullKit(kit) {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p', 'mm', 'letter');
  const pw = 216;
  let page = 1;

  // Cover page
  doc.setFillColor(42, 157, 143);
  doc.rect(0, 0, pw, 50, 'F');
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(kit.title, pw / 2, 30, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${kit.session_count} Sessions | Grades ${kit.grade_range}`, pw / 2, 42, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  doc.text(doc.splitTextToSize(kit.description, pw - 40), 20, 65);

  // Each session
  kit.sessions.forEach((s, i) => {
    doc.addPage();
    let y = 20;

    // Session header
    doc.setFillColor(42, 157, 143);
    doc.roundedRect(15, y, pw - 30, 16, 4, 4, 'F');
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(`Session ${s.session_number}: ${s.title}`, pw / 2, y + 11, { align: 'center' });
    y += 24;

    // Objective
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(42, 157, 143);
    doc.text('Objective:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const objLines = doc.splitTextToSize(s.objective, pw - 40);
    doc.text(objLines, 20, y);
    y += objLines.length * 5 + 6;

    const sections = [
      { label: 'Opening Activity', text: s.opening_activity },
      { label: 'Main Activity', text: s.main_activity },
      { label: 'Closing Check-Out', text: s.closing_checkout },
      { label: 'Take-Home Challenge', text: s.take_home_challenge },
    ];

    sections.forEach(({ label, text }) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(42, 157, 143);
      doc.text(label, 20, y);
      y += 5;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(text, pw - 40);
      // Check if lines fit on page
      if (y + lines.length * 4.5 > 265) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines, 20, y);
      y += lines.length * 4.5 + 8;
    });
  });

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Beacon | clearpathedgroup.com', pw / 2, 272, { align: 'center' });
  }

  doc.save(`${kit.title.replace(/\s+/g, '-')}-Starter-Kit.pdf`);
}

/* ══════════════════════════════════════════════════════
   Component
   ══════════════════════════════════════════════════════ */
export default function ResourcesPage() {
  const [activeSection, setActiveSection] = useState('prompts');
  const [promptTab, setPromptTab] = useState('icebreakers');
  const [gradeFilter, setGradeFilter] = useState('All');
  const [shuffled, setShuffled] = useState(null);
  const [expandedCards, setExpandedCards] = useState({});
  const [expandedKit, setExpandedKit] = useState(null);
  const [expandedSessions, setExpandedSessions] = useState({});
  const [generating, setGenerating] = useState(null);

  const toggleCard = (id) => setExpandedCards((p) => ({ ...p, [id]: !p[id] }));
  const toggleSession = (key) => setExpandedSessions((p) => ({ ...p, [key]: !p[key] }));

  /* ── Session Prompts data ── */
  const promptData = useMemo(() => {
    let items = [];
    if (promptTab === 'icebreakers') items = ICEBREAKERS;
    else if (promptTab === 'scenarios') items = SCENARIO_CARDS;
    else items = MINDFULNESS_SCRIPTS;
    return items.filter((i) => matchesGradeFilter(i.gradeRange, gradeFilter));
  }, [promptTab, gradeFilter]);

  const handleShuffle = useCallback(() => {
    if (promptData.length === 0) { setShuffled(null); return; }
    const idx = Math.floor(Math.random() * promptData.length);
    setShuffled(promptData[idx]);
  }, [promptData]);

  /* ── Visual Resources split ── */
  const printableVisuals = VISUAL_RESOURCES.filter((v) => v.id !== 'vis-6' && v.id !== 'vis-7');
  const safetyPlan = VISUAL_RESOURCES.find((v) => v.id === 'vis-6');
  const crisisCard = VISUAL_RESOURCES.find((v) => v.id === 'vis-7');

  const handlePrintPdf = async (resource) => {
    setGenerating(resource.id);
    try {
      const doc = await resource.generatePdf();
      doc.save(`${resource.title.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
    setGenerating(null);
  };

  const handlePrintKit = async (kit) => {
    setGenerating(kit.id);
    try {
      await printFullKit(kit);
    } catch (err) {
      console.error('Kit PDF generation failed:', err);
    }
    setGenerating(null);
  };

  /* ── Section tabs ── */
  const SECTIONS = [
    { key: 'prompts', label: 'Session Prompts' },
    { key: 'kits', label: 'Group Starter Kits' },
    { key: 'visuals', label: 'Printable Visuals' },
    { key: 'crisis', label: 'Crisis Resources' },
  ];

  return (
    <div className="page">
      <h1 className="page-title" style={{ margin: '0 0 16px' }}>Resources</h1>

      {/* Top-level section tabs */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' }}>
        {SECTIONS.map((s) => (
          <button key={s.key} onClick={() => { setActiveSection(s.key); setShuffled(null); }} style={topTab(activeSection === s.key)}>
            {s.label}
          </button>
        ))}
      </div>

      {/* ═══ SECTION 1: SESSION PROMPTS ═══ */}
      {activeSection === 'prompts' && (
        <div>
          {/* Sub-tabs + grade filter */}
          <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap', alignItems: 'center' }}>
            <button onClick={() => { setPromptTab('icebreakers'); setShuffled(null); }} style={sectionTab(promptTab === 'icebreakers')}>Icebreakers</button>
            <button onClick={() => { setPromptTab('scenarios'); setShuffled(null); }} style={sectionTab(promptTab === 'scenarios')}>Scenario Cards</button>
            <button onClick={() => { setPromptTab('mindfulness'); setShuffled(null); }} style={sectionTab(promptTab === 'mindfulness')}>Mindfulness Scripts</button>
            <div style={{ flex: 1 }} />
            <select
              className="form-input"
              value={gradeFilter}
              onChange={(e) => { setGradeFilter(e.target.value); setShuffled(null); }}
              style={{ width: 120 }}
            >
              {GRADE_FILTERS.map((g) => <option key={g} value={g}>{g === 'All' ? 'All Grades' : `Grades ${g}`}</option>)}
            </select>
            <button className="btn btn-primary" onClick={handleShuffle} style={{ whiteSpace: 'nowrap' }}>
              Shuffle
            </button>
          </div>

          {/* Shuffle spotlight */}
          {shuffled && (
            <div style={{ ...card, marginBottom: 16, borderLeft: '4px solid #2A9D8F', background: '#f0fdfa' }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: '#2A9D8F', marginBottom: 6 }}>Random Pick</div>
              {promptTab === 'icebreakers' && (
                <>
                  <p style={{ fontSize: 15, color: '#1a2332', margin: 0 }}>{shuffled.text}</p>
                  <span style={badge('#e6f7f5', '#2A9D8F')}>{shuffled.gradeRange}</span>
                </>
              )}
              {promptTab === 'scenarios' && (
                <>
                  <p style={{ fontSize: 15, color: '#1a2332', margin: '0 0 8px' }}>{shuffled.scenario}</p>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    <span style={badge('#e6f7f5', '#2A9D8F')}>{shuffled.gradeRange}</span>
                    <span style={badge('#f3e8ff', '#7c3aed')}>{shuffled.topic}</span>
                  </div>
                  <ul style={{ margin: '8px 0 0', paddingLeft: 18, color: '#4b5563', fontSize: 13 }}>
                    {shuffled.discussion_questions.map((q, i) => <li key={i} style={{ marginBottom: 4 }}>{q}</li>)}
                  </ul>
                </>
              )}
              {promptTab === 'mindfulness' && (
                <>
                  <p style={{ fontSize: 15, fontWeight: 600, color: '#1a2332', margin: '0 0 4px' }}>{shuffled.title}</p>
                  <div style={{ display: 'flex', gap: 6, marginBottom: 8 }}>
                    <span style={badge('#e6f7f5', '#2A9D8F')}>{shuffled.gradeRange}</span>
                    <span style={badge('#dbeafe', '#2563eb')}>{shuffled.duration}</span>
                  </div>
                  <p style={{ fontSize: 13, color: '#4b5563', lineHeight: 1.6, margin: 0, whiteSpace: 'pre-line' }}>{shuffled.script}</p>
                </>
              )}
            </div>
          )}

          {/* Cards grid */}
          {promptData.length === 0 ? (
            <div style={{ ...card, textAlign: 'center', padding: 40 }}>
              <p style={{ color: '#9ca3af' }}>No prompts match this grade filter.</p>
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 14 }}>
              {promptData.map((item) => (
                <div key={item.id} style={card}>
                  {/* Icebreakers */}
                  {promptTab === 'icebreakers' && (
                    <>
                      <p style={{ fontSize: 14, color: '#1a2332', margin: '0 0 8px', lineHeight: 1.5 }}>{item.text}</p>
                      <span style={badge('#e6f7f5', '#2A9D8F')}>{item.gradeRange}</span>
                    </>
                  )}
                  {/* Scenario Cards */}
                  {promptTab === 'scenarios' && (
                    <>
                      <p style={{ fontSize: 14, color: '#1a2332', margin: '0 0 8px', lineHeight: 1.5 }}>{item.scenario}</p>
                      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 6 }}>
                        <span style={badge('#e6f7f5', '#2A9D8F')}>{item.gradeRange}</span>
                        <span style={badge('#f3e8ff', '#7c3aed')}>{item.topic}</span>
                      </div>
                      <button onClick={() => toggleCard(item.id)} style={expandBtn}>
                        {expandedCards[item.id] ? 'Hide Questions' : 'Show Discussion Questions'}
                      </button>
                      {expandedCards[item.id] && (
                        <ul style={{ margin: '6px 0 0', paddingLeft: 18, color: '#4b5563', fontSize: 13 }}>
                          {item.discussion_questions.map((q, i) => <li key={i} style={{ marginBottom: 4 }}>{q}</li>)}
                        </ul>
                      )}
                    </>
                  )}
                  {/* Mindfulness Scripts */}
                  {promptTab === 'mindfulness' && (
                    <>
                      <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1a2332', margin: '0 0 6px' }}>{item.title}</h3>
                      <div style={{ display: 'flex', gap: 6, marginBottom: 6 }}>
                        <span style={badge('#e6f7f5', '#2A9D8F')}>{item.gradeRange}</span>
                        <span style={badge('#dbeafe', '#2563eb')}>{item.duration}</span>
                      </div>
                      <button onClick={() => toggleCard(item.id)} style={expandBtn}>
                        {expandedCards[item.id] ? 'Hide Script' : 'Show Full Script'}
                      </button>
                      {expandedCards[item.id] && (
                        <p style={{ margin: '8px 0 0', fontSize: 13, color: '#4b5563', lineHeight: 1.6, whiteSpace: 'pre-line' }}>
                          {item.script}
                        </p>
                      )}
                    </>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* ═══ SECTION 2: GROUP STARTER KITS ═══ */}
      {activeSection === 'kits' && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 14 }}>
          {GROUP_STARTER_KITS.map((kit) => {
            const isExpanded = expandedKit === kit.id;
            return (
              <div key={kit.id} style={{ ...card, display: 'flex', flexDirection: 'column' }}>
                <h3 style={{ fontSize: 16, fontWeight: 700, color: '#1a2332', margin: '0 0 6px' }}>{kit.title}</h3>
                <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 10px', lineHeight: 1.5 }}>{kit.description}</p>
                <div style={{ display: 'flex', gap: 6, marginBottom: 10, flexWrap: 'wrap' }}>
                  <span style={badge('#e6f7f5', '#2A9D8F')}>Grades {kit.grade_range}</span>
                  <span style={badge('#dbeafe', '#2563eb')}>{kit.session_count} sessions</span>
                  <span style={badge('#fef3c7', '#92400e')}>{kit.asca_domain}</span>
                </div>

                <div style={{ display: 'flex', gap: 8, marginBottom: isExpanded ? 12 : 0 }}>
                  <button onClick={() => setExpandedKit(isExpanded ? null : kit.id)} style={expandBtn}>
                    {isExpanded ? 'Collapse Sessions' : 'View All Sessions'}
                  </button>
                  <button
                    onClick={() => handlePrintKit(kit)}
                    disabled={generating === kit.id}
                    style={{
                      ...expandBtn,
                      color: '#6366f1',
                    }}
                  >
                    {generating === kit.id ? 'Generating...' : 'Print Full Kit (PDF)'}
                  </button>
                </div>

                {/* Expanded sessions accordion */}
                {isExpanded && (
                  <div style={{ borderTop: '1px solid #e5e7eb', paddingTop: 10 }}>
                    {kit.sessions.map((s) => {
                      const sKey = `${kit.id}-${s.session_number}`;
                      const sOpen = expandedSessions[sKey];
                      return (
                        <div key={sKey} style={{ marginBottom: 8 }}>
                          <button
                            onClick={() => toggleSession(sKey)}
                            style={{
                              width: '100%',
                              textAlign: 'left',
                              background: sOpen ? '#f0fdfa' : '#f9fafb',
                              border: '1px solid #e5e7eb',
                              borderRadius: 8,
                              padding: '10px 14px',
                              cursor: 'pointer',
                              display: 'flex',
                              justifyContent: 'space-between',
                              alignItems: 'center',
                            }}
                          >
                            <span>
                              <span style={{ fontWeight: 700, color: '#2A9D8F', marginRight: 8 }}>Session {s.session_number}</span>
                              <span style={{ fontWeight: 600, color: '#1a2332', fontSize: 14 }}>{s.title}</span>
                            </span>
                            <span style={{ color: '#9ca3af', fontSize: 18 }}>{sOpen ? '\u2212' : '+'}</span>
                          </button>
                          {sOpen && (
                            <div style={{ padding: '12px 14px', border: '1px solid #e5e7eb', borderTop: 'none', borderRadius: '0 0 8px 8px', background: '#fff' }}>
                              <p style={{ fontSize: 13, color: '#2A9D8F', fontWeight: 600, margin: '0 0 4px' }}>Objective</p>
                              <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{s.objective}</p>

                              <p style={{ fontSize: 13, color: '#2A9D8F', fontWeight: 600, margin: '0 0 4px' }}>Opening Activity</p>
                              <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{s.opening_activity}</p>

                              <p style={{ fontSize: 13, color: '#2A9D8F', fontWeight: 600, margin: '0 0 4px' }}>Main Activity</p>
                              <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{s.main_activity}</p>

                              <p style={{ fontSize: 13, color: '#2A9D8F', fontWeight: 600, margin: '0 0 4px' }}>Closing Check-Out</p>
                              <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{s.closing_checkout}</p>

                              <p style={{ fontSize: 13, color: '#2A9D8F', fontWeight: 600, margin: '0 0 4px' }}>Take-Home Challenge</p>
                              <p style={{ fontSize: 13, color: '#4b5563', margin: 0, lineHeight: 1.5 }}>{s.take_home_challenge}</p>
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* ═══ SECTION 3: PRINTABLE VISUALS ═══ */}
      {activeSection === 'visuals' && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 14 }}>
          {printableVisuals.map((res) => (
            <div key={res.id} style={card}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
                <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1a2332', margin: 0 }}>{res.title}</h3>
                <span style={badge(
                  res.type === 'poster' ? '#dbeafe' : res.type === 'card' ? '#fef3c7' : '#f3e8ff',
                  res.type === 'poster' ? '#2563eb' : res.type === 'card' ? '#92400e' : '#7c3aed',
                )}>
                  {res.type}
                </span>
              </div>
              <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{res.description}</p>
              <button
                className="btn btn-primary"
                onClick={() => handlePrintPdf(res)}
                disabled={generating === res.id}
                style={{ fontSize: 13 }}
              >
                {generating === res.id ? 'Generating...' : 'Print PDF'}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* ═══ SECTION 4: CRISIS RESOURCES ═══ */}
      {activeSection === 'crisis' && (
        <div>
          <div style={{
            border: '2px solid #fca5a5',
            borderRadius: 12,
            padding: 20,
            background: '#fef2f2',
            marginBottom: 16,
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <span style={{ fontSize: 18, color: '#dc2626' }}>&#9888;</span>
              <h2 style={{ fontSize: 17, fontWeight: 700, color: '#991b1b', margin: 0 }}>Crisis Resources</h2>
            </div>
            <p style={{ fontSize: 13, color: '#7f1d1d', margin: '0 0 16px', lineHeight: 1.5 }}>
              These resources are for crisis situations. The Safety Plan is a student-facing worksheet.
              The Crisis Response Quick-Reference is for counselor use only.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 14 }}>
              {/* Safety Plan */}
              {safetyPlan && (
                <div style={{ ...card, borderLeft: '4px solid #22c55e' }}>
                  <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1a2332', margin: '0 0 6px' }}>{safetyPlan.title}</h3>
                  <span style={badge('#dcfce7', '#166534')}>worksheet</span>
                  <p style={{ fontSize: 13, color: '#4b5563', margin: '8px 0 12px', lineHeight: 1.5 }}>{safetyPlan.description}</p>
                  <button
                    className="btn btn-primary"
                    onClick={() => handlePrintPdf(safetyPlan)}
                    disabled={generating === safetyPlan.id}
                    style={{ fontSize: 13 }}
                  >
                    {generating === safetyPlan.id ? 'Generating...' : 'Print PDF'}
                  </button>
                </div>
              )}

              {/* Crisis Response Card */}
              {crisisCard && (
                <div style={{ ...card, borderLeft: '4px solid #ef4444' }}>
                  <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1a2332', margin: '0 0 6px' }}>{crisisCard.title}</h3>
                  <div style={{ display: 'flex', gap: 6, marginBottom: 8 }}>
                    <span style={badge('#fee2e2', '#991b1b')}>card</span>
                    <span style={badge('#fef3c7', '#92400e')}>Counselor Use Only</span>
                  </div>
                  <p style={{ fontSize: 13, color: '#4b5563', margin: '0 0 12px', lineHeight: 1.5 }}>{crisisCard.description}</p>
                  <button
                    className="btn btn-primary"
                    onClick={() => handlePrintPdf(crisisCard)}
                    disabled={generating === crisisCard.id}
                    style={{ fontSize: 13, background: '#dc2626', borderColor: '#dc2626' }}
                  >
                    {generating === crisisCard.id ? 'Generating...' : 'Print PDF'}
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Emergency numbers box */}
          <div style={{ ...card, background: '#fffbeb', borderLeft: '4px solid #f59e0b' }}>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: '#92400e', margin: '0 0 8px' }}>Emergency Numbers</h3>
            <ul style={{ margin: 0, paddingLeft: 18, color: '#78350f', fontSize: 13, lineHeight: 1.8 }}>
              <li><strong>988 Suicide & Crisis Lifeline</strong> -- Call or text 988</li>
              <li><strong>Crisis Text Line</strong> -- Text HOME to 741741</li>
              <li><strong>CPS (Texas)</strong> -- 1-800-252-5400</li>
              <li><strong>National Child Abuse Hotline</strong> -- 1-800-422-4453</li>
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}
