import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { db } from '../lib/db';
import { TIME_DOMAINS } from '../lib/constants';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const COUNSELING_DOMAINS = ['guidance', 'planning', 'responsive'];

/* ─── Helpers ─── */
const TEAL = [42, 157, 143];
const NAVY = [26, 35, 50];
const GRAY = [100, 100, 100];
const BLACK = [30, 30, 30];
const MARGIN = 18;
const PAGE_W = 215.9; // letter mm
const PAGE_H = 279.4;
const CONTENT_W = PAGE_W - MARGIN * 2;

function today() {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function shortDate() {
  return new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' });
}

/** Draw the standard Beacon header bar + title */
function drawHeader(doc, title, subtitle) {
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Beacon', MARGIN, 15);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Clear Path Education Group, LLC', MARGIN, 25);

  doc.setTextColor(...NAVY);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, 46);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY);
    doc.text(subtitle, MARGIN, 54);
  }
}

/** Add footer to every page */
function drawFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by Beacon | clearpathedgroup.com', MARGIN, PAGE_H - 8);
    if (pageCount > 1) {
      doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 8, { align: 'right' });
    }
  }
}

/** Draw a labeled field with an underline */
function drawField(doc, label, x, y, lineW) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text(label, x, y);
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(x, y + 2, x + lineW, y + 2);
  return y + 10;
}

/** Draw pre-filled label: value */
function drawInfo(doc, label, value, x, y) {
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  const labelText = `${label}: `;
  doc.text(labelText, x, y);
  const labelW = doc.getTextWidth(labelText);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  doc.text(value || '', x + labelW, y);
  return y + 7;
}

/** Draw a section heading */
function drawSection(doc, text, y) {
  doc.setFillColor(240, 245, 245);
  doc.rect(MARGIN, y - 4, CONTENT_W, 8, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEAL);
  doc.text(text, MARGIN + 3, y + 1.5);
  return y + 12;
}

/** Draw lined area */
function drawLines(doc, y, count, x, w) {
  x = x || MARGIN;
  w = w || CONTENT_W;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  for (let i = 0; i < count; i++) {
    const ly = y + i * 7;
    doc.line(x, ly, x + w, ly);
  }
  return y + count * 7 + 3;
}

/** Draw checkbox options */
function drawCheckboxes(doc, options, x, y, cols) {
  cols = cols || 2;
  const colW = CONTENT_W / cols;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  options.forEach((opt, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const cx = x + col * colW;
    const cy = y + row * 7;
    doc.setDrawColor(120, 120, 120);
    doc.setLineWidth(0.3);
    doc.rect(cx, cy - 3, 3.5, 3.5);
    doc.text(opt, cx + 5.5, cy);
  });
  const rows = Math.ceil(options.length / cols);
  return y + rows * 7 + 3;
}

/** Signature block */
function drawSignature(doc, label, y) {
  doc.setDrawColor(120, 120, 120);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, MARGIN + 80, y);
  doc.line(MARGIN + 90, y, MARGIN + 130, y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(label, MARGIN, y + 5);
  doc.text('Date', MARGIN + 90, y + 5);
  return y + 14;
}

/** Dual signature block */
function drawDualSignature(doc, label1, label2, y) {
  const halfW = CONTENT_W / 2 - 5;
  doc.setDrawColor(120, 120, 120);
  doc.setLineWidth(0.3);
  // Left
  doc.line(MARGIN, y, MARGIN + halfW, y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(label1, MARGIN, y + 5);
  // Right
  const rx = MARGIN + halfW + 10;
  doc.line(rx, y, rx + halfW, y);
  doc.text(label2, rx, y + 5);
  return y + 14;
}

/** Check if we need a new page */
function checkPage(doc, y, needed) {
  if (y + needed > PAGE_H - 20) {
    doc.addPage();
    return 20;
  }
  return y;
}

/* ─── Template Definitions ─── */

const SECTIONS = [
  {
    title: 'Parent Communication',
    color: '#2A9D8F',
    templates: [
      { id: 'referral_ack', name: 'Referral Acknowledgment Letter', desc: 'Notify parents a referral was received', needsStudent: true },
      { id: 'group_permission', name: 'Small Group Permission Slip', desc: 'Parent consent for group counseling', needsStudent: true },
      { id: 'parent_conference', name: 'Parent Conference Summary', desc: 'Document a parent meeting', needsStudent: true },
      { id: 'progress_update', name: 'Progress Update Letter', desc: 'Periodic update to parents on services', needsStudent: true },
      { id: 'service_closure', name: 'Service Closure Letter', desc: 'Student transitioning out of services', needsStudent: true },
    ],
  },
  {
    title: 'Teacher Communication',
    color: '#3B82F6',
    templates: [
      { id: 'teacher_referral_confirm', name: 'Teacher Referral Confirmation', desc: 'Close the loop with referring teacher', needsStudent: true },
      { id: 'classroom_observation', name: 'Classroom Observation Summary', desc: 'Notes from observing a student in class', needsStudent: true },
      { id: 'teacher_consultation', name: 'Teacher Consultation Notes', desc: 'Document a teacher check-in', needsStudent: true },
    ],
  },
  {
    title: 'Compliance / Documentation',
    color: '#F59E0B',
    templates: [
      { id: 'sb179_time_log', name: 'SB 179 Time Log Summary', desc: 'Auto-generated from your time entries (YTD, with 80/20 compliance)', needsStudent: false },
      { id: 'caseload_summary', name: 'Caseload Summary Report', desc: 'All students by tier', needsStudent: false },
      { id: 'suicide_screening', name: 'Suicide Risk Screening Documentation', desc: 'CRITICAL safety documentation', needsStudent: true, critical: true },
      { id: 'mandated_report', name: 'Mandated Report Documentation', desc: 'CPS/DFPS report record', needsStudent: true, critical: true },
    ],
  },
  {
    title: 'Student-Facing',
    color: '#8B5CF6',
    templates: [
      { id: 'student_goal_sheet', name: 'Student Goal Sheet', desc: 'Simple goal tracker for elementary students', needsStudent: true },
      { id: 'feelings_checkin', name: 'Feelings Check-In Form', desc: 'Session opener for elementary students', needsStudent: true },
    ],
  },
];

/* ════════════════════════════════════════════════════════════════
   PDF GENERATORS
   ════════════════════════════════════════════════════════════════ */

function generateReferralAck(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Referral Acknowledgment Letter');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y += 5;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  doc.text('Dear Parent/Guardian,', MARGIN, y);
  y += 8;
  const intro = doc.splitTextToSize(
    `We have received a referral for your child, ${student?.name || '[Student Name]'}, for school counseling services. ` +
    'This letter is to inform you of the referral and the next steps we will take to support your child.',
    CONTENT_W
  );
  doc.text(intro, MARGIN, y);
  y += intro.length * 5 + 8;

  y = drawSection(doc, 'Referral Details', y);
  y = drawField(doc, 'Referral Source:', MARGIN, y, CONTENT_W);
  y = drawCheckboxes(doc, ['Teacher', 'Parent/Guardian', 'Self-Referral', 'Administrator', 'Other'], MARGIN, y, 3);
  y += 2;
  y = drawField(doc, 'Referral Reason:', MARGIN, y, CONTENT_W);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Planned Response', y);
  y = drawField(doc, 'Planned Services:', MARGIN, y, CONTENT_W);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);
  y = drawField(doc, 'Estimated Start Date:', MARGIN, y, 80);
  y += 5;

  y = checkPage(doc, y, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  const closing = doc.splitTextToSize(
    'Please do not hesitate to contact me if you have any questions or concerns. ' +
    'We look forward to working with your family to support your child\'s success.',
    CONTENT_W
  );
  doc.text(closing, MARGIN, y);
  y += closing.length * 5 + 10;

  doc.setFontSize(10);
  doc.setTextColor(...BLACK);
  doc.text('Sincerely,', MARGIN, y);
  y += 12;
  y = drawSignature(doc, 'School Counselor', y);

  drawFooter(doc);
  doc.save(`Referral-Acknowledgment-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateGroupPermission(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Small Group Permission Slip', 'Parent Consent for Group Counseling');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y += 5;

  y = drawSection(doc, 'Group Information', y);
  y = drawField(doc, 'Group Topic / Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Meeting Schedule (Day / Time / Frequency):', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Duration (Weeks):', MARGIN, y, 60);
  y = drawField(doc, 'Session Length:', MARGIN, y, 60);
  y += 2;
  y = drawField(doc, 'What the Group Covers:', MARGIN, y, CONTENT_W);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Confidentiality', y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  const confNote = doc.splitTextToSize(
    'Group members are expected to keep what is shared in the group confidential. ' +
    'However, the counselor is required to break confidentiality if a student is in danger ' +
    'of harming themselves or others, or if abuse or neglect is suspected.',
    CONTENT_W
  );
  doc.text(confNote, MARGIN, y);
  y += confNote.length * 4.5 + 8;

  y = checkPage(doc, y, 65);
  y = drawSection(doc, 'Parent/Guardian Consent', y);
  y = drawCheckboxes(doc, [
    'I GIVE permission for my child to participate in this group.',
    'I DO NOT give permission for my child to participate.',
  ], MARGIN, y, 1);
  y += 5;

  y = drawDualSignature(doc, 'Parent/Guardian Signature', 'Date', y);
  y += 3;
  y = drawField(doc, 'Parent/Guardian Printed Name:', MARGIN, y, CONTENT_W);
  y += 5;
  y = drawField(doc, 'Please return this form by:', MARGIN, y, 80);

  drawFooter(doc);
  doc.save(`Group-Permission-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateParentConference(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Parent Conference Summary');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y += 5;

  y = drawSection(doc, 'Conference Details', y);
  y = drawField(doc, 'Conference Date:', MARGIN, y, 60);
  y += 2;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Attendees:', MARGIN, y);
  y += 5;
  y = drawCheckboxes(doc, ['Parent/Guardian', 'Teacher', 'Counselor', 'Principal', 'Other: ____________'], MARGIN, y, 3);

  y += 3;
  y = drawSection(doc, 'Concerns Discussed', y);
  y = drawLines(doc, y, 6, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 50);
  y = drawSection(doc, 'Action Items / Plan', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y = drawField(doc, 'Follow-Up Date:', MARGIN, y, 60);
  y = checkPage(doc, y, 30);
  y += 8;
  y = drawDualSignature(doc, 'Counselor Signature', 'Parent/Guardian Signature', y);

  drawFooter(doc);
  doc.save(`Parent-Conference-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateProgressUpdate(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Progress Update Letter');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y += 5;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  doc.text('Dear Parent/Guardian,', MARGIN, y);
  y += 8;
  const intro = doc.splitTextToSize(
    `This letter is to provide you with an update on the counseling services your child, ${student?.name || '[Student Name]'}, has been receiving.`,
    CONTENT_W
  );
  doc.text(intro, MARGIN, y);
  y += intro.length * 5 + 8;

  y = drawSection(doc, 'Service Details', y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Service Type:', MARGIN, y);
  y += 5;
  y = drawCheckboxes(doc, ['Individual Counseling', 'Small Group Counseling'], MARGIN, y, 2);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Tier Level:', MARGIN, y);
  y += 5;
  y = drawCheckboxes(doc, ['Tier 1 (Universal)', 'Tier 2 (Targeted)', 'Tier 3 (Intensive)'], MARGIN, y, 3);
  y = drawField(doc, 'Weeks in Service:', MARGIN, y, 50);

  y = drawSection(doc, 'Progress Summary', y);
  y = drawField(doc, 'Areas of Focus:', MARGIN, y, CONTENT_W);
  y = drawLines(doc, y, 2, MARGIN, CONTENT_W);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Progress Summary:', MARGIN, y);
  y += 4;
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 50);
  y = drawSection(doc, 'Recommendations', y);
  y = drawCheckboxes(doc, ['Continue current services', 'Modify plan', 'Transition to different tier', 'Close services'], MARGIN, y, 2);
  y += 2;
  y = drawField(doc, 'Next Update Date:', MARGIN, y, 60);
  y += 8;
  y = drawSignature(doc, 'School Counselor', y);

  drawFooter(doc);
  doc.save(`Progress-Update-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateServiceClosure(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Service Closure Letter');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y += 5;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BLACK);
  doc.text('Dear Parent/Guardian,', MARGIN, y);
  y += 8;
  const intro = doc.splitTextToSize(
    `This letter is to inform you that counseling services for your child, ${student?.name || '[Student Name]'}, will be concluding. ` +
    'Below is a summary of the services provided and the progress made.',
    CONTENT_W
  );
  doc.text(intro, MARGIN, y);
  y += intro.length * 5 + 8;

  y = drawSection(doc, 'Service Summary', y);
  y = drawField(doc, 'Service Type:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Duration of Services:', MARGIN, y, 80);
  y += 2;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Goals Addressed:', MARGIN, y);
  y += 4;
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Outcomes / Progress:', MARGIN, y);
  y += 4;
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 60);
  y = drawSection(doc, 'Reason for Closure', y);
  y = drawCheckboxes(doc, ['Goals met', 'Parent request', 'Student moved', 'End of school year', 'Other: ____________'], MARGIN, y, 3);

  y += 3;
  y = drawSection(doc, 'Recommendations for Continued Support at Home', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y += 5;
  y = drawSignature(doc, 'School Counselor', y);

  drawFooter(doc);
  doc.save(`Service-Closure-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateTeacherReferralConfirm(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Teacher Referral Confirmation');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y += 5;

  y = drawSection(doc, 'Referral Information', y);
  y = drawField(doc, 'Teacher Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Referral Date Received:', MARGIN, y, 80);
  y = drawField(doc, 'Referral Concern:', MARGIN, y, CONTENT_W);
  y = drawLines(doc, y, 2, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Planned Response', y);
  y = drawCheckboxes(doc, [
    'Individual sessions', 'Small group', 'Classroom observation',
    'Parent contact', 'Outside referral', 'Other: ____________',
  ], MARGIN, y, 3);
  y += 2;
  y = drawField(doc, 'Estimated Timeline:', MARGIN, y, 80);
  y += 5;

  y = drawSection(doc, 'Confidentiality Reminder', y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GRAY);
  const confNote = doc.splitTextToSize(
    'Please remember that the specific details of counseling sessions are confidential. ' +
    'I will share relevant strategies and general progress updates that can help support this student in the classroom. ' +
    'Thank you for your partnership in supporting this student.',
    CONTENT_W
  );
  doc.text(confNote, MARGIN, y);
  y += confNote.length * 4.5 + 10;

  y = drawSignature(doc, 'School Counselor', y);

  drawFooter(doc);
  doc.save(`Teacher-Referral-Confirm-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateClassroomObservation(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Classroom Observation Summary');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y += 5;

  y = drawSection(doc, 'Observation Details', y);
  y = drawField(doc, 'Teacher Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Class / Subject:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Observation Date:', MARGIN, y, 60);
  y = drawField(doc, 'Observation Duration:', MARGIN, y, 60);
  y += 2;

  y = drawSection(doc, 'Behaviors Observed', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Antecedents / Triggers Noted', y);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 50);
  y = drawSection(doc, 'Peer Interactions', y);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Academic Engagement Level', y);
  y = drawCheckboxes(doc, ['Fully Engaged', 'Partially Engaged', 'Disengaged', 'Disruptive'], MARGIN, y, 2);

  y += 3;
  y = drawSection(doc, 'Recommendations', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y += 5;
  y = drawSignature(doc, 'School Counselor', y);

  drawFooter(doc);
  doc.save(`Classroom-Observation-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateTeacherConsultation(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Teacher Consultation Notes');

  let y = 62;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y += 5;

  y = drawSection(doc, 'Consultation Details', y);
  y = drawField(doc, 'Teacher Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Consultation Date:', MARGIN, y, 60);
  y += 2;

  y = drawSection(doc, 'Concerns Discussed', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Strategies Recommended', y);
  y = drawLines(doc, y, 5, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 40);
  y = drawSection(doc, 'Resources Provided', y);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = drawField(doc, 'Follow-Up Date:', MARGIN, y, 60);
  y += 8;
  y = drawDualSignature(doc, 'Counselor Signature', 'Teacher Signature', y);

  drawFooter(doc);
  doc.save(`Teacher-Consultation-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

async function generateSB179TimeLog(counselor) {
  const now = new Date();
  const syStart = counselor?.school_year_start
    || (now.getMonth() >= 7 ? `${now.getFullYear()}-08-01` : `${now.getFullYear() - 1}-08-01`);
  const syEnd = counselor?.school_year_end
    || (now.getMonth() >= 7 ? `${now.getFullYear() + 1}-07-31` : `${now.getFullYear()}-07-31`);

  const { data: entries } = await db.select('time_entries', {
    eq: { counselor_id: counselor.id },
    gte: { entry_date: syStart },
    lte: { entry_date: syEnd },
    order: { column: 'entry_date', ascending: true },
  });
  const rows = entries || [];

  const byDomain = {};
  Object.keys(TIME_DOMAINS).forEach(k => { byDomain[k] = 0; });
  rows.forEach(e => { byDomain[e.domain] = (byDomain[e.domain] || 0) + (e.duration_minutes || 0); });
  const totalMin = Object.values(byDomain).reduce((a, b) => a + b, 0);
  const directMin = COUNSELING_DOMAINS.reduce((s, d) => s + (byDomain[d] || 0), 0);
  const indirectMin = totalMin - directMin;
  const pct = totalMin > 0 ? (directMin / totalMin) * 100 : 0;
  const compliant = pct >= 80;

  const firstDate = rows[0]?.entry_date || syStart;
  const lastDate = rows[rows.length - 1]?.entry_date || shortDate();
  const periodLabel = `${firstDate} through ${lastDate}`;

  const doc = new jsPDF({ format: 'letter' });
  drawHeader(doc, 'SB 179 Time Log Summary', 'School Year Service Hour Report');

  let y = 62;
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.school_name || counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Reporting Period', periodLabel, MARGIN, y);
  y = drawInfo(doc, 'Date Generated', today(), MARGIN, y);
  y += 4;

  y = drawSection(doc, 'Direct Counseling Services (SB 179)', y);
  COUNSELING_DOMAINS.forEach(k => {
    const hrs = ((byDomain[k] || 0) / 60).toFixed(1);
    y = drawInfo(doc, TIME_DOMAINS[k], `${hrs} hrs`, MARGIN + 4, y);
  });
  y = drawInfo(doc, 'Total Direct', `${(directMin / 60).toFixed(1)} hrs`, MARGIN + 4, y);
  y += 3;

  y = drawSection(doc, 'Indirect / Non-Counseling', y);
  ['system', 'non_counseling'].forEach(k => {
    const hrs = ((byDomain[k] || 0) / 60).toFixed(1);
    y = drawInfo(doc, TIME_DOMAINS[k], `${hrs} hrs`, MARGIN + 4, y);
  });
  y = drawInfo(doc, 'Total Indirect', `${(indirectMin / 60).toFixed(1)} hrs`, MARGIN + 4, y);
  y += 4;

  y = checkPage(doc, y, 40);
  y = drawSection(doc, '80/20 Compliance', y);
  y = drawInfo(doc, 'Total Hours Logged', `${(totalMin / 60).toFixed(1)} hrs`, MARGIN, y);
  y = drawInfo(doc, 'Direct Service Percentage', `${pct.toFixed(1)}%`, MARGIN, y);
  y = drawInfo(doc, 'Compliance Status', compliant ? 'In Compliance (80%+ direct)' : 'Below Threshold', MARGIN, y);
  y += 3;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GRAY);
  const note = doc.splitTextToSize(
    'Per SB 179 (TEC §33.006), school counselors shall spend at least 80% of work time on direct counseling services. Hours shown are auto-computed from time entries logged in Beacon during the reporting period.',
    CONTENT_W
  );
  doc.text(note, MARGIN, y);
  y += note.length * 4 + 6;

  if (rows.length > 0) {
    y = checkPage(doc, y, 20);
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Domain', 'Activity', 'Min']],
      body: rows.map(e => [
        e.entry_date,
        TIME_DOMAINS[e.domain] || e.domain,
        (e.activity_description || '').slice(0, 60),
        e.duration_minutes,
      ]),
      headStyles: { fillColor: TEAL, fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 1.5 },
      margin: { left: MARGIN, right: MARGIN },
      columnStyles: { 0: { cellWidth: 22 }, 3: { cellWidth: 14, halign: 'right' } },
    });
    y = doc.lastAutoTable.finalY + 8;
  }

  y = checkPage(doc, y, 30);
  y = drawDualSignature(doc, 'Counselor Signature', 'Principal Review Signature', y);

  drawFooter(doc);
  doc.save(`SB179-Time-Log-${shortDate()}.pdf`);
}

function generateCaseloadSummary(counselor) {
  const doc = new jsPDF({ format: 'letter' });
  const now = new Date();
  const schoolYear = now.getMonth() >= 7
    ? `${now.getFullYear()}-${now.getFullYear() + 1}`
    : `${now.getFullYear() - 1}-${now.getFullYear()}`;
  drawHeader(doc, 'Caseload Summary Report');

  let y = 62;
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'School Year', schoolYear, MARGIN, y);
  y += 5;

  // Tier 3 table
  y = drawSection(doc, 'Tier 3 — Intensive (Individual Counseling)', y);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  const cols = ['Student Name', 'Grade', 'Service Type', 'Weeks in Service', 'Status'];
  const colWidths = [50, 20, 40, 35, 35];
  let cx = MARGIN;
  cols.forEach((col, i) => {
    doc.text(col, cx, y);
    cx += colWidths[i];
  });
  y += 2;
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
  y += 2;
  // Empty rows
  for (let r = 0; r < 6; r++) {
    y = drawLines(doc, y, 1, MARGIN, CONTENT_W);
  }

  y = checkPage(doc, y, 60);
  y = drawSection(doc, 'Tier 2 — Targeted (Small Group)', y);
  cx = MARGIN;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  cols.forEach((col, i) => {
    doc.text(col, cx, y);
    cx += colWidths[i];
  });
  y += 2;
  doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
  y += 2;
  for (let r = 0; r < 6; r++) {
    y = drawLines(doc, y, 1, MARGIN, CONTENT_W);
  }

  y = checkPage(doc, y, 40);
  y = drawSection(doc, 'Tier 1 — Universal', y);
  y = drawField(doc, 'Total Students Served:', MARGIN, y, 50);
  y = drawField(doc, 'Classroom Lessons Delivered:', MARGIN, y, 50);
  y += 5;

  y = drawSection(doc, 'Summary', y);
  y = drawField(doc, 'Total Caseload Count:', MARGIN, y, 50);
  y = drawField(doc, 'Staffing Ratio:', MARGIN, y, 50);
  y += 8;

  y = drawSignature(doc, 'Principal Signature', y);

  drawFooter(doc);
  doc.save(`Caseload-Summary-${shortDate()}.pdf`);
}

function generateSuicideScreening(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Suicide Risk Screening Documentation');

  // Confidentiality banner
  doc.setFillColor(239, 68, 68);
  doc.rect(MARGIN, 50, CONTENT_W, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('CONFIDENTIAL: This document contains sensitive mental health information', MARGIN + 3, 57);

  let y = 68;
  y = drawInfo(doc, 'Student', sName, MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y += 3;

  y = drawSection(doc, 'Disclosure Information', y);
  y = drawField(doc, 'Date/Time of Disclosure:', MARGIN, y, 80);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('How Disclosed:', MARGIN, y);
  y += 5;
  y = drawCheckboxes(doc, [
    'Verbal to counselor', 'Verbal to teacher', 'Written',
    'Behavioral indicators', 'Peer report', 'Other',
  ], MARGIN, y, 3);

  y = drawSection(doc, 'Screening Questions Asked', y);
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 60);
  y = drawSection(doc, 'Risk Level Determined', y);
  y = drawCheckboxes(doc, ['Low', 'Moderate', 'High', 'Imminent'], MARGIN, y, 4);

  y = drawSection(doc, 'Actions Taken', y);
  y = drawCheckboxes(doc, [
    'Parent/guardian notified', 'Principal notified', 'Safety plan created',
    'Crisis team activated', 'Outside referral made', '911 called', 'Student not left alone',
  ], MARGIN, y, 2);

  y = checkPage(doc, y, 60);
  y = drawSection(doc, 'Parent Notification', y);
  y = drawField(doc, 'Date:', MARGIN, y, 50);
  y = drawField(doc, 'Time:', MARGIN, y, 50);
  y = drawField(doc, 'Person Contacted:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Method of Contact:', MARGIN, y, 80);

  y = drawSection(doc, 'Safety Plan Details', y);
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 50);
  y = drawSection(doc, 'Follow-Up Plan', y);
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  y = drawSection(doc, 'Outside Referrals Made', y);
  y = drawLines(doc, y, 3, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 30);
  y += 3;
  y = drawDualSignature(doc, 'Counselor Signature (Date/Time)', 'Administrator Signature', y);

  drawFooter(doc);
  doc.save(`Suicide-Screening-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateMandatedReport(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';
  drawHeader(doc, 'Mandated Report Documentation', 'CPS / DFPS Report Record');

  // Warning banner
  doc.setFillColor(239, 68, 68);
  doc.rect(MARGIN, 56, CONTENT_W, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('DO NOT investigate \u2014 report and document only', MARGIN + 3, 63);

  let y = 74;
  y = drawInfo(doc, 'Counselor', counselor?.name || '', MARGIN, y);
  y = drawInfo(doc, 'Campus', counselor?.campus || '', MARGIN, y);
  y = drawInfo(doc, 'Date', today(), MARGIN, y);
  y += 3;

  y = drawSection(doc, 'Student Information', y);
  y = drawField(doc, 'Student Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Date/Time of Disclosure or Observation:', MARGIN, y, CONTENT_W);
  y += 2;

  y = drawSection(doc, 'Nature of Concern', y);
  y = drawCheckboxes(doc, ['Physical abuse', 'Sexual abuse', 'Emotional abuse', 'Neglect', 'Other: ____________'], MARGIN, y, 3);

  y = drawSection(doc, 'Description of What Was Disclosed / Observed', y);
  y = drawLines(doc, y, 6, MARGIN, CONTENT_W);

  y = checkPage(doc, y, 60);
  y = drawSection(doc, 'Report Details', y);
  y = drawField(doc, 'Reporter Information:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'CPS/DFPS Call Date and Time:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Intake Worker Name:', MARGIN, y, CONTENT_W);
  y = drawField(doc, 'Case / Reference Number:', MARGIN, y, CONTENT_W);
  y += 2;

  y = drawSection(doc, 'Additional Actions Taken', y);
  y = drawCheckboxes(doc, [
    'Principal notified', 'Nurse notified',
    'Law enforcement contacted', 'Student safe plan created',
  ], MARGIN, y, 2);

  y = checkPage(doc, y, 40);
  y = drawSection(doc, 'Follow-Up Plan', y);
  y = drawLines(doc, y, 4, MARGIN, CONTENT_W);

  y += 3;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GRAY);
  const legal = doc.splitTextToSize(
    'Per Texas Family Code \u00A7261.101, professionals have a duty to report suspected child abuse or neglect within 48 hours.',
    CONTENT_W
  );
  doc.text(legal, MARGIN, y);
  y += legal.length * 4 + 8;

  y = drawSignature(doc, 'Counselor Signature (Date/Time)', y);

  drawFooter(doc);
  doc.save(`Mandated-Report-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateStudentGoalSheet(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';

  // Friendly header for elementary students
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('My Goal Sheet', MARGIN, 18);

  let y = 38;
  doc.setTextColor(...NAVY);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Name:', MARGIN, y);
  doc.setFont('helvetica', 'normal');
  doc.text(sName, MARGIN + 25, y);
  doc.setFontSize(11);
  y += 8;
  doc.text(`Date: ${today()}`, MARGIN, y);
  y += 10;

  // Goal
  doc.setFillColor(240, 250, 248);
  doc.roundedRect(MARGIN, y, CONTENT_W, 32, 3, 3, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEAL);
  doc.text('My goal is:', MARGIN + 5, y + 10);
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(MARGIN + 5, y + 17, MARGIN + CONTENT_W - 5, y + 17);
  doc.line(MARGIN + 5, y + 24, MARGIN + CONTENT_W - 5, y + 24);
  y += 40;

  // Steps
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Steps I will take:', MARGIN, y);
  y += 6;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  for (let i = 1; i <= 5; i++) {
    doc.text(`${i}.`, MARGIN + 4, y);
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN + 12, y + 1, MARGIN + CONTENT_W, y + 1);
    y += 7;
  }
  y += 5;

  // People who can help
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('People who can help me:', MARGIN, y);
  y += 6;
  for (let i = 0; i < 3; i++) {
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN + 4, y + 1, MARGIN + CONTENT_W, y + 1);
    y += 7;
  }
  y += 5;

  // Success criteria
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('I will know I reached my goal when:', MARGIN, y);
  y += 6;
  for (let i = 0; i < 3; i++) {
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN + 4, y + 1, MARGIN + CONTENT_W, y + 1);
    y += 9;
  }
  y += 5;

  // Check-in dates
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Check-in dates:', MARGIN, y);
  y += 7;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  for (let i = 1; i <= 3; i++) {
    doc.text(`Check-in ${i}:`, MARGIN + 4, y);
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN + 35, y + 1, MARGIN + 80, y + 1);
    y += 8;
  }
  y += 5;

  // Self-rating scale
  y = checkPage(doc, y, 50);
  doc.setFillColor(255, 250, 235);
  doc.roundedRect(MARGIN, y, CONTENT_W, 22, 3, 3, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('How do I feel about my progress?', MARGIN + 5, y + 8);
  doc.setFontSize(16);
  const faces = ['\u2639', '\u2639', '\ud83d\ude10', '\u263A', '\u263A'];
  // Use text labels instead of emoji for PDF compatibility
  const faceLabels = ['Not Good', 'A Little', 'OK', 'Good', 'Great!'];
  const faceX = MARGIN + 10;
  for (let i = 0; i < 5; i++) {
    const cx = faceX + i * 35;
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.5);
    doc.circle(cx + 5, y + 16, 4);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY);
    doc.text(faceLabels[i], cx - 1, y + 22, { align: 'left' });
  }
  y += 30;

  // Signatures
  y = drawDualSignature(doc, 'Student Signature', 'Counselor Signature', y);

  drawFooter(doc);
  doc.save(`Goal-Sheet-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

function generateFeelingsCheckin(counselor, student) {
  const doc = new jsPDF({ format: 'letter' });
  const sName = student?.name || '________________________';

  // Kid-friendly header
  doc.setFillColor(139, 92, 246); // purple
  doc.rect(0, 0, PAGE_W, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Feelings Check-In', MARGIN, 19);

  let y = 38;
  doc.setTextColor(...NAVY);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Name:', MARGIN, y);
  doc.setFont('helvetica', 'normal');
  doc.text(sName, MARGIN + 25, y);
  doc.setFontSize(11);
  y += 8;
  doc.text(`Date: ${today()}`, MARGIN, y);
  y += 12;

  // Emotion circles
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Today I feel:', MARGIN, y);
  y += 8;

  const emotions = [
    { label: 'Happy', color: [34, 197, 94] },
    { label: 'Sad', color: [59, 130, 246] },
    { label: 'Angry', color: [239, 68, 68] },
    { label: 'Worried', color: [245, 158, 11] },
    { label: 'Confused', color: [139, 92, 246] },
  ];

  const circleR = 12;
  const spacing = CONTENT_W / emotions.length;
  emotions.forEach((em, i) => {
    const cx = MARGIN + spacing * i + spacing / 2;
    doc.setDrawColor(...em.color);
    doc.setLineWidth(1);
    doc.setFillColor(255, 255, 255);
    doc.circle(cx, y + circleR, circleR, 'FD');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...em.color);
    doc.text(em.label, cx, y + circleR + circleR + 6, { align: 'center' });
  });
  y += circleR * 2 + 16;

  // Something that happened
  y += 5;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Something that happened:', MARGIN, y);
  y += 5;
  for (let i = 0; i < 5; i++) {
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
    y += 8;
  }
  y += 3;

  // What would help
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('What would help me feel better:', MARGIN, y);
  y += 5;
  for (let i = 0; i < 5; i++) {
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
    y += 8;
  }
  y += 5;

  // Feeling scale
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('On a scale of 1\u20135, how big is this feeling?', MARGIN, y);
  y += 8;
  const scaleSpacing = CONTENT_W / 6;
  for (let i = 1; i <= 5; i++) {
    const cx = MARGIN + scaleSpacing * i;
    doc.setDrawColor(139, 92, 246);
    doc.setLineWidth(0.8);
    doc.setFillColor(255, 255, 255);
    doc.circle(cx, y, 8, 'FD');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(139, 92, 246);
    doc.text(String(i), cx, y + 1.5, { align: 'center' });
    // Labels for 1 and 5
    if (i === 1) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...GRAY);
      doc.text('Small', cx, y + 12, { align: 'center' });
    }
    if (i === 5) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...GRAY);
      doc.text('Really Big', cx, y + 12, { align: 'center' });
    }
  }
  y += 22;

  // Counselor notes
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GRAY);
  doc.text('Counselor Notes (for counselor use only):', MARGIN, y);
  y += 4;
  for (let i = 0; i < 3; i++) {
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.15);
    doc.line(MARGIN, y, MARGIN + CONTENT_W, y);
    y += 6;
  }

  drawFooter(doc);
  doc.save(`Feelings-CheckIn-${student?.name?.replace(/\s+/g, '-') || 'Student'}-${shortDate()}.pdf`);
}

/* ─── Generator dispatch ─── */
const GENERATORS = {
  referral_ack: generateReferralAck,
  group_permission: generateGroupPermission,
  parent_conference: generateParentConference,
  progress_update: generateProgressUpdate,
  service_closure: generateServiceClosure,
  teacher_referral_confirm: generateTeacherReferralConfirm,
  classroom_observation: generateClassroomObservation,
  teacher_consultation: generateTeacherConsultation,
  sb179_time_log: generateSB179TimeLog,
  caseload_summary: generateCaseloadSummary,
  suicide_screening: generateSuicideScreening,
  mandated_report: generateMandatedReport,
  student_goal_sheet: generateStudentGoalSheet,
  feelings_checkin: generateFeelingsCheckin,
};

/* ════════════════════════════════════════════════════════════════
   PAGE COMPONENT
   ════════════════════════════════════════════════════════════════ */

export default function TemplatesPage() {
  const { counselor } = useAuth();
  const [students, setStudents] = useState([]);
  const [selectedStudents, setSelectedStudents] = useState({}); // { templateId: studentId }
  const [generating, setGenerating] = useState(null);

  // Load active students for the student selector
  useEffect(() => {
    if (!counselor?.id) return;
    (async () => {
      const { data } = await db.select('students', {
        eq: { counselor_id: counselor.id, status: 'active' },
        order: { column: 'name', ascending: true },
      });
      setStudents(data || []);
    })();
  }, [counselor?.id]);

  const handleGenerate = useCallback(async (templateId, needsStudent) => {
    setGenerating(templateId);
    try {
      const generator = GENERATORS[templateId];
      if (!generator) return;

      let student = null;
      if (needsStudent) {
        const sid = selectedStudents[templateId];
        if (sid) {
          student = students.find(s => s.id === sid) || null;
        }
      }
      await generator(counselor, student);
    } catch (err) {
      console.error('PDF generation error:', err);
    } finally {
      setGenerating(null);
    }
  }, [counselor, students, selectedStudents]);

  const handleStudentChange = useCallback((templateId, studentId) => {
    setSelectedStudents(prev => ({ ...prev, [templateId]: studentId }));
  }, []);

  return (
    <div style={{ maxWidth: 960, margin: '0 auto' }}>
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text)', margin: 0 }}>
          Document Templates
        </h1>
        <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', marginTop: 4 }}>
          Generate professional PDF documents for parent communication, teacher collaboration, compliance, and student activities.
          {students.length > 0 ? ` Select a student from your caseload to pre-fill templates.` : ''}
        </p>
      </div>

      {SECTIONS.map(section => (
        <div key={section.title} style={{ marginBottom: 28 }}>
          {/* Section header */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12,
            paddingBottom: 8, borderBottom: `2px solid ${section.color}`,
          }}>
            <div style={{
              width: 10, height: 10, borderRadius: '50%',
              background: section.color, flexShrink: 0,
            }} />
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text)', margin: 0 }}>
              {section.title}
            </h2>
            <span style={{
              fontSize: '0.75rem', color: 'var(--text-muted)',
              background: 'var(--bg)', padding: '2px 8px', borderRadius: 10,
            }}>
              {section.templates.length}
            </span>
          </div>

          {/* Template cards */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: 12,
          }}>
            {section.templates.map(tmpl => (
              <div key={tmpl.id} style={{
                background: 'var(--card-bg)', border: '1px solid var(--border)',
                borderRadius: 10, padding: 16,
                borderLeft: tmpl.critical ? '3px solid #ef4444' : `3px solid ${section.color}`,
                display: 'flex', flexDirection: 'column', gap: 8,
              }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
                  <div>
                    <h3 style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text)', margin: 0, lineHeight: 1.3 }}>
                      {tmpl.name}
                    </h3>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', margin: '4px 0 0', lineHeight: 1.4 }}>
                      {tmpl.desc}
                    </p>
                  </div>
                  {tmpl.critical && (
                    <span style={{
                      fontSize: '0.65rem', fontWeight: 700, color: '#ef4444',
                      background: '#fef2f2', padding: '2px 6px', borderRadius: 4,
                      whiteSpace: 'nowrap', flexShrink: 0, marginLeft: 8,
                    }}>
                      CRITICAL
                    </span>
                  )}
                </div>

                {/* Student selector */}
                {tmpl.needsStudent && students.length > 0 && (
                  <select
                    value={selectedStudents[tmpl.id] || ''}
                    onChange={e => handleStudentChange(tmpl.id, e.target.value)}
                    style={{
                      width: '100%', padding: '6px 8px', borderRadius: 6,
                      border: '1px solid var(--border)', fontSize: '0.8rem',
                      color: 'var(--text)', background: 'var(--card-bg)',
                    }}
                  >
                    <option value="">Select student (optional)</option>
                    {students.map(s => (
                      <option key={s.id} value={s.id}>
                        {s.name}{s.grade ? ` (Grade ${s.grade})` : ''}
                      </option>
                    ))}
                  </select>
                )}

                {tmpl.needsStudent && students.length === 0 && (
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 0, fontStyle: 'italic' }}>
                    No active students — template will generate with blank fields
                  </p>
                )}

                {/* Generate button */}
                <button
                  onClick={() => handleGenerate(tmpl.id, tmpl.needsStudent)}
                  disabled={generating === tmpl.id}
                  style={{
                    marginTop: 'auto', padding: '8px 14px', borderRadius: 6,
                    border: 'none', cursor: generating === tmpl.id ? 'wait' : 'pointer',
                    fontSize: '0.8rem', fontWeight: 600,
                    background: tmpl.critical ? '#ef4444' : section.color,
                    color: '#fff',
                    opacity: generating === tmpl.id ? 0.6 : 1,
                    transition: 'opacity 0.15s',
                  }}
                >
                  {generating === tmpl.id ? 'Generating...' : 'Generate PDF'}
                </button>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
